Pequenos Erros
Ludeon/RimWorld-PortugueseBrazilian pull request #125
Opened 2021-06-23 14:43 UTC by KitsuneModder

E um gigante...

2021-06-28 12:00 UTC, KitsuneModder commented
?

2021-07-09 18:40 UTC, KitsuneModder commented
O que está com "bug"?

@LoboMetalurgico

2021-07-09 19:48 UTC, LoboMetalurgico commented
A tag bug em um issue indica que ele está relacionado a um bug, já em um pull request, indica que corrige um bug. Sendo assim, a tag bug aqui trata das suas correções das traduções já feitas. Depois vou tirar um tempo e colocar descrição nas tags.

Eu ainda não terminei a review, e tem algumas coisas para alterar. São coisas simples, não se preocupe.

2021-07-09 20:12 UTC, KitsuneModder commented
Ok! Obrigado :)

2021-07-13 17:47 UTC, arxdsilva commented
@LoboMetalurgico @KitsuneModder, acredito que podemos mergear esse e caso necessitem mais mudancas fazemos em outros PRs menores, o que acham?

2021-07-13 18:34 UTC, LoboMetalurgico commented
> @LoboMetalurgico @KitsuneModder, acredito que podemos mergear esse e caso necessitem mais mudancas fazemos em outros PRs menores, o que acham?

Vou publicar a review até onde parei. Uma das correções se não feita vai causar problema, mas é coisa simples.

2021-07-13 18:36 UTC, LoboMetalurgico requested changes
Olá, aqui estão algumas alterações. São simples e poucas, já que foi uma revisão parcial. O resto podemos corrigir em PR's menores, como indicado por @arxdsilva.

2021-07-13 19:08 UTC, KitsuneModder commented
Corrigi os erros que tinha marcado :)

Além de outros que me mandaram :)

2021-07-14 04:46 UTC, LoboMetalurgico approved these changes
Obrigado pelas correções!
Como discutido anteriormente, correções futuras serão feitas em outros PR's.

2021-07-14 04:47 UTC, merged