Quick Update
Ludeon/RimWorld-PortugueseBrazilian pull request #126
Opened 2021-07-14 21:50 UTC by KitsuneModder

Esses ''Quick Updates'' são pequenos updates que foram feitos ao jogo, mesmo enquanto no beta (1.3).

2021-07-19 23:24 UTC, LoboMetalurgico requested changes
Olá, obrigado pelo seu pull request.

Além dos comentários indicando coisas para serem corrigidas, tenho uma pergunta:

Em alguns lugares, "mote" está escrito igual o inglês, mas em outros, está como "partícula". Porque?

2021-07-19 23:24 UTC, LoboMetalurgico commented on Core/DefInjected/InstructionDef/Instructions.xml
> +  <rejectInputMessage.text>Clique em GERAR para gerar seu mundo.</rejectInputMessage.te>
acredido que deveria ser </rejectInputMessage.text>

2021-07-19 23:24 UTC, LoboMetalurgico commented on Royalty/Keyed/Misc_Gameplay.xml
> +  <RitualTargetAnimaTreeNoPawnsToLink>Nenhum colonizo pode se conectar com a árvore anima agora.</RitualTargetAnimaTreeNoPawnsToLink>
não seria melhor usar "colono" ao invés de "colonizo"?

2021-07-20 16:27 UTC, KitsuneModder commented on Core/DefInjected/InstructionDef/Instructions.xml
> +  <rejectInputMessage.text>Clique em GERAR para gerar seu mundo.</rejectInputMessage.te>
Já está corrigido:)

2021-07-20 16:27 UTC, KitsuneModder commented on Royalty/Keyed/Misc_Gameplay.xml
> +  <RitualTargetAnimaTreeNoPawnsToLink>Nenhum colonizo pode se conectar com a árvore anima agora.</RitualTargetAnimaTreeNoPawnsToLink>
Corrigido

2021-07-20 16:29 UTC, KitsuneModder commented
Sobre o Mote/Partícula,

Eu também não sei.

Apenas deixei como estava...

2021-07-20 17:10 UTC, KitsuneModder commented
Como lançou o Ideology

Ele o traduzurei :)

Mas em outro pull request

2021-07-20 18:19 UTC, merged