Bug Correction
Ludeon/RimWorld-PortugueseBrazilian pull request #210
Opened 2021-09-01 17:57 UTC by KitsuneModder

### **📝 Alterações Propostas:**

Corrige os erros indicados no _discord_.

### **📜 Requisitos:**

 - [x] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [x] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

![image](https://user-images.githubusercontent.com/81825142/131720362-4dbfe9d7-5b2c-448e-901d-e8ed1a33d0e7.png)
![image](https://user-images.githubusercontent.com/81825142/131720382-d79c465f-ffe0-4800-a3a7-6567c30d8d85.png)
![image](https://user-images.githubusercontent.com/81825142/131720395-6e1a33d4-91c9-4710-aa01-b98ec12f84a2.png)

2021-09-01 20:18 UTC, LoboMetalurgico requested changes

2021-09-01 20:18 UTC, LoboMetalurgico commented on Core/DefInjected/RulePackDef/RulePacks_CombatRanged.xml
> +    <li>destroyed_suffix(p=0.5)->uma puta bagunça</li>
```suggestion
    <li>destroyed_suffix(p=0.5)->uma grande bagunça</li>
```

2021-09-01 20:18 UTC, LoboMetalurgico commented on Core/DefInjected/RulePackDef/RulePacks_CombatRanged.xml
> +    <li>deflected_result-> [adverb_deflected]</li>
```suggestion
    <li>deflected_result->[adverb_deflected]</li>
```

2021-09-01 20:18 UTC, LoboMetalurgico commented on Core/DefInjected/RulePackDef/RulePacks_CombatRanged.xml
> +    <li>destroyed_suffix(p=0.5)->uma puta bagunça</li>
Vamos evitar esse tipo de termo

2021-09-04 12:11 UTC, KitsuneModder commented on Core/DefInjected/RulePackDef/RulePacks_CombatRanged.xml
> +    <li>deflected_result-> [adverb_deflected]</li>
É necessário o espaço.

Por causa do outro ''deflected_result'':

<li>deflected_result->, [deflected_consequence]</li>

2021-09-04 14:46 UTC, LoboMetalurgico approved these changes

2021-09-04 14:47 UTC, merged