Atualização dos Narradores
Ludeon/RimWorld-PortugueseBrazilian pull request #233
Opened 2022-02-21 22:16 UTC by Kitsune912

### **📝 Alterações Propostas:**

Reescrita das descrições dos narradores.

### **📜 Requisitos:**

 - [x] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [x] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2022-03-01 21:26 UTC, LoboMetalurgico requested changes

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/StorytellerDef/Storytellers.xml
>    <Phoebe.label>Rúbia Relaxante</Phoebe.label>
```suggestion
  <Phoebe.label>Phoebe Relaxante</Phoebe.label>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/StorytellerDef/Storytellers.xml
>    <Phoebe.label>Rúbia Relaxante</Phoebe.label>
Não sei quando foi alterado e nem o porquê, mas sei que não devíamos alterar o nome original.

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/StorytellerDef/Storytellers.xml
> +  <Phoebe.description>A Rúbia lhe proporciona bastante tempo entre desastres para você relaxar e construir sua colônia. Mas cuidado - em altas dificuldades, ela pegará tão pesado como ninguém.</Phoeb
```suggestion
  <Phoebe.description>A Phoebe lhe proporciona bastante tempo entre desastres para você relaxar e construir sua colônia. Mas cuidado - em altas dificuldades, ela pegará tão pesado como ninguém.</Phoebe.description>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/StorytellerDef/Storytellers.xml
>    <Randy.label>Alécio Aleatório</Randy.label>
```suggestion
  <Randy.label>Randy Aleatório</Randy.label>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/StorytellerDef/Storytellers.xml
> +  <Randy.description>O Alécio não segue as regras. Ele manipulará eventos aleatórios sem se importar se a história será de triunfo ou de total desespero. Para ele, a vida é drama.\n\nAviso: Como o Al
```suggestion
  <Randy.description>O Randy não segue as regras. Ele manipulará eventos aleatórios sem se importar se a história será de triunfo ou de total desespero. Para ele, a vida é um drama.\n\nAviso: Como o Randy é realmente aleatório, às vezes, ele manipulará eventos injustos ou extremamente difíceis. É bom que adiciona algum drama... e também alguns sacrifícios.</Randy.description>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Buildings_Production.xml
> +  <HandTailoringBench.label>mesa de alfaiate à mão</HandTailoringBench.label>
```suggestion
  <HandTailoringBench.label>mesa de alfaiate manual</HandTailoringBench.label>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
> +  <Frame_HandTailoringBench.label>mesa de alfaiate à mão (construção)</Frame_HandTailoringBench.label>
```suggestion
  <Frame_HandTailoringBench.label>mesa de alfaiate manual (construção)</Frame_HandTailoringBench.label>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
>    <Frame_Ship_SensorCluster.label>sensor cluster (building)</Frame_Ship_SensorCluster.label>
```suggestion
  <Frame_Ship_SensorCluster.label>sensor de conglomerados (construção)</Frame_Ship_SensorCluster.label>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <ModsChanged>A lista de modificações foi alterada. O jogo reiniciará automaticamente.</ModsChanged>
```suggestion
  <ModsChanged>A lista de mods foi alterada. O jogo reiniciará automaticamente.</ModsChanged>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <ModsChanged>A lista de modificações foi alterada. O jogo reiniciará automaticamente.</ModsChanged>
Apesar de "mods" ser uma palavra de origem inglesa, a maioria, se não todos os jogadores conhecem pelo termo "mods".

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <LoadingAllActiveMods>Carregando Modificações Ativas</LoadingAllActiveMods>
```suggestion
  <LoadingAllActiveMods>Carregando Mods Ativos</LoadingAllActiveMods>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <TranslationFilesTKeyUpdate>Atualizar Arquivos de Tradução (TKey's)</TranslationFilesTKeyUpdate>
```suggestion
  <TranslationFilesTKeyUpdate>Atualizar Arquivos da Tradução (TKey's)</TranslationFilesTKeyUpdate>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <TranslationFilesTKeyUpdate>Atualizar Arquivos de Tradução (TKey's)</TranslationFilesTKeyUpdate>
Consistência com os outros textos.

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <ReloadAnytimeModeInfo>Você pode salvar e carregar o jogo a qualquer momento.\n\nEsta é uma boa opção se: você ainda estiver aprendendo a jogar, seu estilo de jogo se adequar-se a essa configuração
```suggestion
  <ReloadAnytimeModeInfo>Você pode salvar e carregar o jogo a qualquer momento.\n\nEsta é uma boa opção se você ainda estiver aprendendo a jogar, seu estilo de jogo se adequar-se a essa configuração, você estiver usando mods que podem quebrar o jogo ou se você pretende aplicar o modo 'morte pernamente' no futuro.</ReloadAnytimeModeInfo>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <DifficultyReset>Modo de Jogo Padrão Modelo</DifficultyReset>
```suggestion
  <DifficultyReset>Definir Modo de Jogo Padrão</DifficultyReset>
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <DifficultyReset>Modo de Jogo Padrão Modelo</DifficultyReset>
Eu realmente não entendi isso...

2022-03-01 21:26 UTC, LoboMetalurgico commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <ClassicLike.description>Seus colomos recebem um sistema de crenças igual ao do RimWorld clássico. O resto do mundo tem ideologias geradas separas.</ClassicLike.description>
```suggestion
```

2022-03-01 21:26 UTC, LoboMetalurgico commented on Ideology/DefInjected/IdeoPresetDef/IdeoPresetDefs.xml
> +  <ClassicLike.description>Seus colomos recebem um sistema de crenças igual ao do RimWorld clássico. O resto do mundo tem ideologias geradas separas.</ClassicLike.description>
Já existe.

2022-03-01 21:26 UTC, LoboMetalurgico commented on Ideology/Keyed/Misc_Gameplay.xml
> +  <CustomizeIdeoligion>Personalização de Ideologia</CustomizeIdeoligion>
```suggestion
  <CustomizeIdeoligion>Personalização da Ideologia</CustomizeIdeoligion>
```

2022-03-01 23:39 UTC, Kitsune912 commented on Core/Keyed/Menus_Main.xml
> +  <DifficultyReset>Modo de Jogo Padrão Modelo</DifficultyReset>
Eu acho confuso com o "definir", mas ok.

2022-03-01 23:46 UTC, Kitsune912 commented on Core/DefInjected/StorytellerDef/Storytellers.xml
>    <Phoebe.label>Rúbia Relaxante</Phoebe.label>
Eu estou verificando isso... mas de qualquer maneira, farei as alterações.

2022-03-01 23:51 UTC, Kitsune912 commented on Core/Keyed/Dialogs_Various.xml
> +  <ModsChanged>A lista de modificações foi alterada. O jogo reiniciará automaticamente.</ModsChanged>
Vou alterar para 'mod', porém com o gênero feminino e um ponto (como se fosse a abreviação).

2022-03-01 23:55 UTC, Kitsune912 commented
Ah, e sobre os narradores:

Coloquei o primeiro nome em inglês, mas alterei o adjetivo para um similar de modo a manter a coisinha de duas letras iguais (isso é meio que uma farsa por causa da phoebe, mas ok)

2022-03-02 01:18 UTC, LoboMetalurgico requested changes
Apenas mais algumas coisinhas...

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Credits.xml
> +  <Credits_TitleMods>Mods.</Credits_TitleMods>
```suggestion
  <Credits_TitleMods>Mods</Credits_TitleMods>
```

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Credits.xml
> +  <Credits_TitleMods>Mods.</Credits_TitleMods>
Por questão de estética, podemos nos dar a "licença poética" e ignorar esse e outros pontos relacionados com a palavra "mod"

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Credits.xml
> +  <Credit_ModDonation>Doadores de Mods.</Credit_ModDonation>
```suggestion
  <Credit_ModDonation>Doadores de Mods</Credit_ModDonation>
```

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Dialog_StatsReports.xml
> +  <Stat_Source_ModReport>Este conteúdo veio de uma mod.</Stat_Source_ModReport>
```suggestion
  <Stat_Source_ModReport>Este conteúdo veio de um mod.</Stat_Source_ModReport>
```

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <ModsChanged>A lista de mods. foi alterada. O jogo reiniciará automaticamente.</ModsChanged>
```suggestion
  <ModsChanged>A lista de mods foi alterada. O jogo reiniciará automaticamente.</ModsChanged>
```

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <LoadingAllActiveMods>Carregando Mods. Ativas</LoadingAllActiveMods>
```suggestion
  <LoadingAllActiveMods>Carregando Mods Ativos</LoadingAllActiveMods>
```

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Menu_Options.xml
> +  <TextureCompression_Tooltip>Desativar a compactação de textura usará muito mais memória de vídeo, mas faz com que as texturas pareçam um pouco melhores em áreas detalhadas. Desative-o apenas se sou
```suggestion
  <TextureCompression_Tooltip>Desativar a compactação de textura usará muito mais memória de vídeo, mas faz com que as texturas pareçam um pouco melhores em áreas detalhadas. Desative-o apenas se souber que tem muita memória de vídeo extra.\n\nObserve que o uso de certos mods geralmente consome muito mais memória de vídeo, portanto, pode ser necessário ativá-lo se adicionar certos mods.</TextureCompression_Tooltip>
```

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <ResolveModOrder>Organizar Mods.</ResolveModOrder>
```suggestion
  <ResolveModOrder>Organizar Mods</ResolveModOrder>
```

2022-03-02 01:18 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <ReloadAnytimeModeInfo>Você pode salvar e carregar o jogo a qualquer momento.\n\nEsta é uma boa opção se você ainda estiver aprendendo a jogar, seu estilo de jogo se adequar-se a essa configuração,
```suggestion
  <ReloadAnytimeModeInfo>Você pode salvar e carregar o jogo a qualquer momento.\n\nEsta é uma boa opção se você ainda estiver aprendendo a jogar, seu estilo de jogo se adequar a essa configuração, você estiver usando mods que podem quebrar o jogo ou se você pretende aplicar o modo 'morte permamente' no futuro.</ReloadAnytimeModeInfo>
```

2022-03-02 23:58 UTC, LoboMetalurgico approved these changes

2022-03-02 23:58 UTC, merged