Pequenas Correções
Ludeon/RimWorld-PortugueseBrazilian pull request #238
Opened 2022-03-12 17:41 UTC by Kitsune912

### **📝 Alterações Propostas:**
Só arrumando algumas coisinhas.

### **📜 Requisitos:**

 - [x] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [x] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2022-03-22 21:26 UTC, LoboMetalurgico requested changes
Apenas algumas alterações precisam ser revistas.
Como de costume, qualquer alteração pode ser discutida através da sessão de comentários.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <InsultingSpree.label>voleio de xingamentos</InsultingSpree.label>
```suggestion
  <InsultingSpree.label>disparando xingamentos</InsultingSpree.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <InsultingSpree.label>voleio de xingamentos</InsultingSpree.label>
Apesar de não ser o mais correto, "voleio" é uma tradução muito estranha para isso.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <InsultingSpree.baseInspectLine>Estado Mental: Voleio de Xingamentos</InsultingSpree.baseInspectLine>
```suggestion
  <InsultingSpree.baseInspectLine>Estado Mental: Disparando Xingamentos</InsultingSpree.baseInspectLine>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <TargetedInsultingSpree.label>voleio de xingamentos</TargetedInsultingSpree.label>
```suggestion
  <TargetedInsultingSpree.label>Disparando xingamentos</TargetedInsultingSpree.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <TargetedInsultingSpree.baseInspectLine>Estado Mental: Voleio de Xingamentos na Mãe de {0}</TargetedInsultingSpree.baseInspectLine>
```suggestion
  <TargetedInsultingSpree.baseInspectLine>Estado Mental: Disparando Xingamentos sobre a Mãe de {0}</TargetedInsultingSpree.baseInspectLine>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <Wander_OwnRoom.baseInspectLine>Estado Mental: Esconde-Esconde</Wander_OwnRoom.baseInspectLine>
```suggestion
  <Wander_OwnRoom.baseInspectLine>Estado Mental: Se Escondendo no Quarto</Wander_OwnRoom.baseInspectLine>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <Wander_OwnRoom.baseInspectLine>Estado Mental: Esconde-Esconde</Wander_OwnRoom.baseInspectLine>
Esconde-Esconde não está exatamente correto, visto que o colono afetado realmente se isola no próprio quarto.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <Wander_Sad.label>tristeza</Wander_Sad.label>
```suggestion
  <Wander_Sad.label>depressão</Wander_Sad.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
> +  <Wander_Sad.baseInspectLine>Estado Mental: Tristeza</Wander_Sad.baseInspectLine>
```suggestion
  <Wander_Sad.baseInspectLine>Estado Mental: Deprimido</Wander_Sad.baseInspectLine>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Manhunter.label>caça aos humanos</Manhunter.label>
```suggestion
  <Manhunter.label>caçador de humanos</Manhunter.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Manhunter.label>caça aos humanos</Manhunter.label>
Acredito que seja mais adequado.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <Manhunter.baseInspectLine>Enlouquecido: Caça aos Humanos</Manhunter.baseInspectLine>
```suggestion
  <Manhunter.baseInspectLine>Enlouquecido: Caçador de Humanos</Manhunter.baseInspectLine>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <ManhunterPermanent.label>caça aos humanos</ManhunterPermanent.label>
```suggestion
  <ManhunterPermanent.label>caçador de humanos</ManhunterPermanent.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <ManhunterPermanent.baseInspectLine>Enlouquecido: Caça aos Humanos</ManhunterPermanent.baseInspectLine>
```suggestion
  <ManhunterPermanent.baseInspectLine>Enlouquecido: Caçador de Humanos</ManhunterPermanent.baseInspectLine>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <WanderConfused.label>ócio confuso</WanderConfused.label>
```suggestion
  <WanderConfused.label>vagando confuso</WanderConfused.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <WanderConfused.label>ócio confuso</WanderConfused.label>
Mais apropriado.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/MentalStateDef/MentalStates_Special.xml
> +  <WanderConfused.baseInspectLine>Estado mental: Ócio Confuso</WanderConfused.baseInspectLine>
```suggestion
  <WanderConfused.baseInspectLine>Estado mental: Vagando Confuso</WanderConfused.baseInspectLine>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/RecipeDef/Items_Exotic.xml
> +  <AdministerMechSerumHealer.label>administrar meca-soro de cura</AdministerMechSerumHealer.label>
```suggestion
  <AdministerMechSerumHealer.label>administrar soro mech de cura</AdministerMechSerumHealer.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/RecipeDef/Items_Exotic.xml
> +  <AdministerMechSerumHealer.label>administrar meca-soro de cura</AdministerMechSerumHealer.label>
Tradução de termo desnecessária.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/RecipeDef/Items_Exotic.xml
> +  <AdministerMechSerumHealer.description>Administrar um meca-soro de cura.</AdministerMechSerumHealer.description>
```suggestion
  <AdministerMechSerumHealer.description>Administrar soro mech de cura.</AdministerMechSerumHealer.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/RecipeDef/Items_Exotic.xml
> +  <AdministerMechSerumHealer.jobString>Administrando meca-soro de cura.</AdministerMechSerumHealer.jobString>
```suggestion
  <AdministerMechSerumHealer.jobString>Administrando soro mech de cura.</AdministerMechSerumHealer.jobString>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Buildings_Misc.xml
> +  <CaravanPackingSpot.description>Um local onde as caravanas serão formadas. Colonos prenderão os animais aqui enquanto carregam a caravana. Você também pode usar durante encontros longe de casa para
```suggestion
  <CaravanPackingSpot.description>Designa um local onde as caravanas serão formadas. Colonos prenderão os animais aqui enquanto carregam a caravana. Você também pode usar durante encontros longe de casa para evitar que os animais vaguem.</CaravanPackingSpot.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Buildings_Misc.xml
> +  <CaravanPackingSpot.description>Um local onde as caravanas serão formadas. Colonos prenderão os animais aqui enquanto carregam a caravana. Você também pode usar durante encontros longe de casa para
Correção inconsistente com a tradução original.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Buildings_Misc.xml
> +  <MarriageSpot.description>Um local onde cerimônias de casamento acontecerão. Os espectadores podem assistir de qualquer lado.</MarriageSpot.description>
```suggestion
  <MarriageSpot.description>Designa um local onde cerimônias de casamento acontecerão. Os espectadores podem assistir de qualquer lado.</MarriageSpot.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Buildings_Misc.xml
> +  <PartySpot.description>Um local onde festas serão concentradas. Festam acontecerão em torno do ponto.</PartySpot.description>
```suggestion
  <PartySpot.description>Designa um local onde festas serão concentradas. Festam acontecerão em torno do ponto.</PartySpot.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
> +  <!-- EN: Um local onde as caravanas serão formadas. Colonos prenderão os animais aqui enquanto carregam a caravana. Você também pode usar durante encontros longe de casa para evitar que os animais
```suggestion
  <!-- EN: Designa um local onde as caravanas serão formadas. Colonos prenderão os animais aqui enquanto carregam a caravana. Você também pode usar durante encontros longe de casa para evitar que os animais vaguem. -->
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
> +  <Frame_CaravanPackingSpot.description>Um local onde as caravanas serão formadas. Colonos prenderão os animais aqui enquanto carregam a caravana. Você também pode usar durante encontros longe de cas
```suggestion
  <Frame_CaravanPackingSpot.description>Designa um local onde as caravanas serão formadas. Colonos prenderão os animais aqui enquanto carregam a caravana. Você também pode usar durante encontros longe de casa para evitar que os animais vaguem.</Frame_CaravanPackingSpot.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
> +  <!-- EN: Um local onde cerimônias de casamento acontecerão. Os espectadores podem assistir de qualquer lado. -->
```suggestion
  <!-- EN: Designa um local onde cerimônias de casamento acontecerão. Os espectadores podem assistir de qualquer lado. -->
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
> +  <Frame_MarriageSpot.description>Um local onde cerimônias de casamento acontecerão. Os espectadores podem assistir de qualquer lado.</Frame_MarriageSpot.description>
```suggestion
  <Frame_MarriageSpot.description>Designa um local onde cerimônias de casamento acontecerão. Os espectadores podem assistir de qualquer lado.</Frame_MarriageSpot.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
> +  <!-- EN: Um local onde festas serão concentradas. Festam acontecerão em torno do local. -->
```suggestion
  <!-- EN: Designa um local onde festas serão concentradas. Festam acontecerão em torno do ponto. -->
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/ImpliedDefs.xml
> +  <Frame_PartySpot.description>Um local onde festas serão concentradas. Festam acontecerão em torno do local.</Frame_PartySpot.description>
```suggestion
  <Frame_PartySpot.description>Designa um local onde festas serão concentradas. Festam acontecerão em torno do ponto.</Frame_PartySpot.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Items_Exotic.xml
> +  <MechSerumHealer.label>meca-soro de cura</MechSerumHealer.label>
```suggestion
  <MechSerumHealer.label>soro mech de cura</MechSerumHealer.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Items_Exotic.xml
> +  <MechSerumHealer.comps.CompUsable.useLabel>Usar o meca-soro de cura</MechSerumHealer.comps.CompUsable.useLabel>
```suggestion
  <MechSerumHealer.comps.CompUsable.useLabel>Usar o soro mech de cura</MechSerumHealer.comps.CompUsable.useLabel>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Items_Exotic.xml
> +  <MechSerumResurrector.label>meca-soro ressuscitador</MechSerumResurrector.label>
```suggestion
  <MechSerumResurrector.label>soro mech ressuscitador</MechSerumResurrector.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Items_Exotic.xml
> +  <MechSerumResurrector.comps.CompUsable.useLabel>Usar o meca-soro ressuscitador</MechSerumResurrector.comps.CompUsable.useLabel>
```suggestion
  <MechSerumResurrector.comps.CompUsable.useLabel>Usar o soro mech ressuscitador</MechSerumResurrector.comps.CompUsable.useLabel>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Items_Resource_Manufactured.xml
> +  <MedicineUltratech.label>medicina purpurante</MedicineUltratech.label>
```suggestion
  <MedicineUltratech.label>medicina de glitterworld</MedicineUltratech.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Items_Resource_Manufactured.xml
> +  <MedicineUltratech.label>medicina purpurante</MedicineUltratech.label>
Tradução de termo desnecessária.

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/Keyed/GameplayCommands.xml
> +  <CommandRemoveWaypointDesc>Remova esse waypoint.</CommandRemoveWaypointDesc>
```suggestion
  <CommandRemoveWaypointDesc>Remover este waypoint.</CommandRemoveWaypointDesc>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/WordInfo/Gender/Singular.txt
> +meca-soro de cura
```suggestion
soro mech de cura
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/WordInfo/Gender/Singular.txt
> +meca-soro ressuscitador
```suggestion
soro mech ressuscitador
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/WordInfo/Gender/new_words.txt
> +meca-soro de cura
```suggestion
soro mech de cura
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Core/WordInfo/Gender/new_words.txt
> +meca-soro ressuscitador
```suggestion
soro mech ressuscitador
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Royalty/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
> +  <CureAbasia.description>Essa operação médica especial usa uma enorme dose de mecanitos para saturar o tecido cerebral e executar uma reestruturação coordenada da atividade neural sem danificar o cé
```suggestion
  <CureAbasia.description>Essa operação médica especial usa uma enorme dose de mecanitos para saturar o tecido cerebral e executar uma reestruturação coordenada da atividade neural sem danificar o cérebro. Cura permanentemente a paralisia induzida por abasia de um paciente, mas consome uma grande quantidade da medicina de glitterworld.</CureAbasia.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Royalty/DefInjected/RoyalTitlePermitDef/RoyalPermits_Empire.xml
> +  <GlitterMedDrop.label>Remessa de medicinas purpurantes</GlitterMedDrop.label>
```suggestion
  <GlitterMedDrop.label>Remessa de medicinas de glitterworld</GlitterMedDrop.label>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Royalty/DefInjected/RoyalTitlePermitDef/RoyalPermits_Empire.xml
> +  <GlitterMedDrop.description>Solicite uma remessa de 5 medicinas purpurantes.</GlitterMedDrop.description>
```suggestion
  <GlitterMedDrop.description>Solicite uma remessa de 5 medicinas de glitterworld.</GlitterMedDrop.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Royalty/DefInjected/ThingDef/Buildings_Misc.xml
> +  <MeditationSpot.description>Um local para meditação. Psinjuradores podem meditar aqui para obter concentração psíquica. Se um objeto de foco como uma escultura estiver próximo, o psinjurador poderá
```suggestion
  <MeditationSpot.description>Designa um local para meditação. Psinjuradores podem meditar aqui para obter concentração psíquica. Se um objeto de foco como uma escultura estiver próximo, o psinjurador poderá focar nele para aumentar seu ganho de concentração psíquica. No entanto, pessoas diferentes podem usar objetos de foco diferentes.</MeditationSpot.description>
```

2022-03-22 21:26 UTC, LoboMetalurgico commented on Royalty/Keyed/Letters.xml
> +  <LetterTextWandererJoinsAbasia>U{0_gender ? m : ma } {0_title} chamad{0_gender ? o : a } {PAWN_nameDef} se acidentou em uma cápsula de transporte por perto.\n\n{PAWN_nameDef} está sofrendo de {1_la
```suggestion
  <LetterTextWandererJoinsAbasia>U{0_gender ? m : ma } {0_title} chamad{0_gender ? o : a } {PAWN_nameDef} se acidentou em uma cápsula de transporte por perto.\n\n{PAWN_nameDef} está sofrendo de {1_label} e não poderá andar.\n\n{0_pronoun} se recuperará naturalmente dentro de vários dias. É possível também que se recupere rapidamente. {1_label}também pode  ser curado(a) através de uma cirurgia especial; que demanda uma grande quantidade de medicamentos de glitterworld.\n\n{0_pronoun} está disposto a colaborar uma vez que estiver recuperad{0_gender ? o : a }, mas não irá embora de maneira voluntária. Caso você não queira {0_nameDef} na sua colônia, você pode bani-l{0_gender ? o : a }, vendê-l{0_gender ? o : a } como escravo ou {0_gender ? o : a } deixar para morrer. No entanto, seus outros colonos podem achar perturbador.</LetterTextWandererJoinsAbasia>
```

2022-03-26 23:10 UTC, Kitsune912 commented on Core/Keyed/GameplayCommands.xml
> +  <CommandRemoveWaypointDesc>Remova esse waypoint.</CommandRemoveWaypointDesc>
Alteração por consistência com descrições de "recipes".

2022-03-27 19:09 UTC, LoboMetalurgico approved these changes

2022-03-27 19:09 UTC, merged