Grammar plus
Ludeon/RimWorld-PortugueseBrazilian pull request #243
Opened 2022-04-10 18:34 UTC by Kitsune912

### **📝 Alterações Propostas:**
Diversas pequenas alterações.

### **📜 Requisitos:**

 - [x] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [x] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2022-04-11 17:03 UTC, LoboMetalurgico requested changes
Olá, obrigado pelas alteração!

Infelizmente não é possível aprovar devido alguns problemas encontrados. Se necessário, forneça mais detalhes na seção de comentários ou via discord.

Após as correções serem efetuadas, ficarei feliz em aprovar este Pull Request.

2022-04-11 17:03 UTC, LoboMetalurgico commented on Core/Keyed/Incidents.xml
> +  <LetterThrumboPasses>Um pequeno rebanho de trumbos se desviou para a área.\n\nPacíficas por natureza, estas criaturas raras são extremamente perigosas quando confrontadas. Alguns comerciantes estão
Qual o motivo desta correção?

2022-04-11 17:03 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <LearningHelper>Auxiliar de Aprend.</LearningHelper>
```suggestion
  <LearningHelper>Auxiliar de Aprendizagem</LearningHelper>
```

2022-04-11 17:03 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <LearningHelper>Auxiliar de Aprend.</LearningHelper>
Qual o motivo da mudança?

2022-04-11 17:03 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <PawnTooltipGenderAndKindLabel>{1} {0}</PawnTooltipGenderAndKindLabel>
```suggestion
  <PawnTooltipGenderAndKindLabel>{0} {1}</PawnTooltipGenderAndKindLabel>
```

2022-04-11 17:03 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <PawnTooltipGenderAndKindLabel>{1} {0}</PawnTooltipGenderAndKindLabel>
Qual o motivo da mudança?

2022-04-12 15:17 UTC, Kitsune912 commented on Core/Keyed/Incidents.xml
> +  <LetterThrumboPasses>Um pequeno rebanho de trumbos se desviou para a área.\n\nPacíficas por natureza, estas criaturas raras são extremamente perigosas quando confrontadas. Alguns comerciantes estão
O gênero é feminino, pois "pacífico" se refere às criaturas, não aos trumbos.

2022-04-12 15:20 UTC, Kitsune912 commented on Core/Keyed/Misc_Gameplay.xml
> +  <LearningHelper>Auxiliar de Aprend.</LearningHelper>
Corte da IU:

![image](https://user-images.githubusercontent.com/81825142/162996681-3c52a8f6-206f-4c5c-a567-c680bb1ae731.png)

2022-04-12 15:21 UTC, Kitsune912 commented on Core/Keyed/ITabs.xml
> +  <ShowSocial>Social</ShowSocial>
Corte da IU:

![image](https://user-images.githubusercontent.com/81825142/162996815-1b694cac-cdc7-4cd5-b6f4-c76aed2328cd.png)

2022-04-12 15:21 UTC, Kitsune912 commented on Core/Keyed/ITabs.xml
> +  <ShowCombat>Combate</ShowCombat>
Corte da IU:

![image](https://user-images.githubusercontent.com/81825142/162996849-4505c76f-5d85-4a8a-a326-7e646acbcf28.png)

2022-04-12 15:21 UTC, Kitsune912 commented on Core/Keyed/ITabs.xml
> +  <ShowAll>Tudo</ShowAll>
Consistência com as alterações seguintes.

2022-04-12 19:02 UTC, LoboMetalurgico commented on Core/Keyed/ITabs.xml
> +  <ShowCombat>Combate</ShowCombat>
E se trocássemos para "Exibir"? Tem apenas uma letra de diferença, mas é possível que ajude a resolver o problema, sem perder a consistência. Qualquer coisa, "Exib." pode ser uma alternativa.

2022-04-12 19:02 UTC, LoboMetalurgico commented on Core/Keyed/ITabs.xml
> +  <ShowSocial>Social</ShowSocial>
E se trocássemos para "Exibir"? Tem apenas uma letra de diferença, mas é possível que ajude a resolver o problema, sem perder a consistência. Qualquer coisa, "Exib." pode ser uma alternativa.

2022-04-12 19:04 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <PawnTooltipGenderAndKindLabel>{1} {0}</PawnTooltipGenderAndKindLabel>
Entendi.

2022-04-12 19:04 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <LearningHelper>Auxiliar de Aprend.</LearningHelper>
Não seria mais adequado cortar o termo "Auxiliar"?

2022-04-12 19:05 UTC, LoboMetalurgico commented on Core/Keyed/Incidents.xml
> +  <LetterThrumboPasses>Um pequeno rebanho de trumbos se desviou para a área.\n\nPacíficas por natureza, estas criaturas raras são extremamente perigosas quando confrontadas. Alguns comerciantes estão
Certo.

2022-04-13 19:22 UTC, Kitsune912 commented on Core/Keyed/ITabs.xml
> +  <ShowCombat>Combate</ShowCombat>
![image](https://user-images.githubusercontent.com/81825142/163254582-bce0c800-9675-44a2-bed6-1c820c729246.png)

Combate continua cortado.

2022-04-13 19:22 UTC, Kitsune912 commented on Core/Keyed/ITabs.xml
> +  <ShowAll>Tudo</ShowAll>
![image](https://user-images.githubusercontent.com/81825142/163254631-c87f6365-15e5-42d0-a142-a3a5cc363082.png)

2022-04-13 19:22 UTC, Kitsune912 commented on Core/Keyed/ITabs.xml
> +  <ShowSocial>Social</ShowSocial>
![image](https://user-images.githubusercontent.com/81825142/163254665-e98f1209-cb4a-4314-92d6-fd5ae1294b22.png)

Combate continua cortado.

2022-04-13 19:22 UTC, Kitsune912 commented on Core/Keyed/Misc_Gameplay.xml
> +  <LearningHelper>Auxiliar de Aprend.</LearningHelper>
Como assim?

Deixar só "Aprendizagem"?

Ou colocar "Aux. de Aprendizagem"?

2022-04-14 16:33 UTC, Kitsune912 commented on Core/Keyed/ITabs.xml
> +  <ShowCombat>Combate</ShowCombat>
A única solução seria colocar "Exib. Comb."

2022-04-17 14:17 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <LearningHelper>Auxiliar de Aprend.</LearningHelper>
Aux. de Aprendizagem

2022-04-17 14:18 UTC, LoboMetalurgico commented on Core/Keyed/ITabs.xml
> +  <ShowSocial>Social</ShowSocial>
Ok.

2022-04-17 14:18 UTC, LoboMetalurgico commented on Core/Keyed/ITabs.xml
> +  <ShowCombat>Combate</ShowCombat>
Talvez seja uma boa alternativa.

2022-04-17 14:19 UTC, LoboMetalurgico commented on Core/DefInjected/PawnColumnDef/PawnColumns_Icon.xml
> +  <LifeStage.label>Fase</LifeStage.label>
Acredito que é tolerável

2022-04-17 14:47 UTC, LoboMetalurgico requested changes
Mais alguma mudanças necessárias

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/DefInjected/ConceptDef/Concepts_TriggeredModal.xml
> +  <SteamDeckControlsMainMenu.helpText>Use o mousepad para mover o mouse. Use o gatilho R2 para o clique esquerdo do mouse. Pressione A para continuar e B para voltar.</SteamDeckControlsMainMenu.helpT
```suggestion
  <SteamDeckControlsMainMenu.helpText>Use o trackpad para mover o mouse. Use o gatilho R2 para o clique esquerdo do mouse. Pressione A para continuar e B para voltar.</SteamDeckControlsMainMenu.helpText>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/DefInjected/ConceptDef/Concepts_TriggeredModal.xml
> +  <SteamDeckControlsMainMenu.helpText>Use o mousepad para mover o mouse. Use o gatilho R2 para o clique esquerdo do mouse. Pressione A para continuar e B para voltar.</SteamDeckControlsMainMenu.helpT
Está correto, de acordo com a documentação oficial do Steam Deck.

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/DefInjected/IncidentDef/Incidents_Map_Threats.xml
> +  <Infestation.letterText>Uma colmeia de insetos surgiu! Ela gerará lentamente insetos como também produzir colmeias adicionais. Se você não quiser que infestem toda a área, reúna suas forças e a des
Se possível, traduza este texto novamente para que fique consistente com o idioma original.

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/DefInjected/ThingDef/Buildings_Natural.xml
> +  <Hive.description>Uma colmeia de insetos que, se ativada, gerá insetos e mais colmeias adicionais ao longo do tempo.</Hive.description>
```suggestion
  <Hive.description>Uma colmeia de insetos que, se ativada, gerará insetos e mais colmeias adicionais ao longo do tempo.</Hive.description>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
> +  <Pain.stages.mindshattering_pain.description>PUTA QUE PARIU! Me mata!</Pain.stages.mindshattering_pain.description>
```suggestion
  <Pain.stages.mindshattering_pain.description>AAAAAHHH! Me mate agora!</Pain.stages.mindshattering_pain.description>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
> +  <Pain.stages.mindshattering_pain.description>PUTA QUE PARIU! Me mata!</Pain.stages.mindshattering_pain.description>
Péssima ideia, é sério.

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBench>Requer</RequiredResearchBench>
```suggestion
  <RequiredResearchBench>Requer Bancada de Pesquisa</RequiredResearchBench>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBench>Requer</RequiredResearchBench>
Inconsistência com o idioma original.

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBenchFacilities>Requer</RequiredResearchBenchFacilities>
Requer Bancada de Pesquisa de Alta Tecnologia

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBenchFacilities>Requer</RequiredResearchBenchFacilities>
Inconsistência com o idioma original.

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <PawnTooltipPsychicEntropyDesc>O calor neural aumenta após a realização de uma psinjuração. Ultrapassar o limite normal pode causar um colapso psíquico que dura dias.\n\nO calor neural dissipa-se n
```suggestion
  <PawnTooltipPsychicEntropyDesc>O calor neural aumenta após a realização de um psycast. Ultrapassar o limite normal pode causar um colapso psíquico que dura dias.\n\nO calor neural dissipa-se naturalmente ao longo do tempo. Esse processo pode ser acelerado usando roupas de eltex ou sentindo dores.</PawnTooltipPsychicEntropyDesc>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/Misc_Gameplay.xml
> +  <PawnTooltipPsychicEntropyDesc>O calor neural aumenta após a realização de uma psinjuração. Ultrapassar o limite normal pode causar um colapso psíquico que dura dias.\n\nO calor neural dissipa-se n
Aquela velha história de ser uma má ideia mudar termos antigos.

2022-04-17 14:47 UTC, LoboMetalurgico commented on Royalty/Keyed/Dialogs_Various.xml
> +  <ApparelRequirementOrAnyPsycasterOrPrestigeApparel>ou qualquer psinjurador ou vestimenta de prestígio</ApparelRequirementOrAnyPsycasterOrPrestigeApparel>
```suggestion
  <ApparelRequirementOrAnyPsycasterOrPrestigeApparel>ou qualquer psycaster ou vestimenta de prestígio</ApparelRequirementOrAnyPsycasterOrPrestigeApparel>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <SelectFoodRestriction>Selecionar Restr. Alimentar</SelectFoodRestriction>
```suggestion
  <SelectFoodRestriction>Selecionar Restrição Alimentar</SelectFoodRestriction>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <SelectFoodRestriction>Selecionar Restr. Alimentar</SelectFoodRestriction>
Qual o motivo da mudança?

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <NewFoodRestriction>Nova Restr. Alimentar</NewFoodRestriction>
```suggestion
  <NewFoodRestriction>Nova Restrição Alimentar</NewFoodRestriction>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <DeleteFoodRestriction>Excluir Restr. Alimentar</DeleteFoodRestriction>
```suggestion
  <DeleteFoodRestriction>Excluir Restrição Alimentar</DeleteFoodRestriction>
```

2022-04-17 14:47 UTC, LoboMetalurgico commented on Core/Keyed/ITabs.xml
> +  <ShowCombat>Exib. Combate</ShowCombat>
```suggestion
  <ShowCombat>Exib. Comb.</ShowCombat>
```

2022-04-17 19:29 UTC, Kitsune912 commented on Core/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
> +  <Pain.stages.mindshattering_pain.description>PUTA QUE PARIU! Me mata!</Pain.stages.mindshattering_pain.description>
KKKKKKKKKKKKKKKK

2022-04-17 19:30 UTC, Kitsune912 commented on Core/Keyed/Misc_Gameplay.xml
> +  <PawnTooltipPsychicEntropyDesc>O calor neural aumenta após a realização de uma psinjuração. Ultrapassar o limite normal pode causar um colapso psíquico que dura dias.\n\nO calor neural dissipa-se n
Já estão todos alterados para _psinjuração_,

Só mantive a consistência.

2022-04-17 19:30 UTC, Kitsune912 commented on Core/Keyed/Dialogs_Various.xml
> +  <SelectFoodRestriction>Selecionar Restr. Alimentar</SelectFoodRestriction>
Corte da I.U.

2022-04-17 19:32 UTC, Kitsune912 commented on Core/Keyed/Dialogs_Various.xml
> +  <NewFoodRestriction>Nova Restr. Alimentar</NewFoodRestriction>
Corte da I.U.

2022-04-17 19:32 UTC, Kitsune912 commented on Core/Keyed/Dialogs_Various.xml
> +  <DeleteFoodRestriction>Excluir Restr. Alimentar</DeleteFoodRestriction>
Corte da I.U.

2022-04-17 20:11 UTC, Kitsune912 commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBenchFacilities>Requer</RequiredResearchBenchFacilities>
![image](https://user-images.githubusercontent.com/81825142/163730577-fd31ba99-0644-4375-ae56-acf96a83e3fc.png)

2022-04-17 20:11 UTC, Kitsune912 commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBench>Requer</RequiredResearchBench>
![image](https://user-images.githubusercontent.com/81825142/163730581-eb862639-6550-4dc2-a1ac-ecfb67f427f9.png)

2022-04-17 20:12 UTC, Kitsune912 commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBench>Requer</RequiredResearchBench>
Não há perda alguma pela remoção.

2022-04-17 20:13 UTC, Kitsune912 commented on Core/Keyed/MainTabs.xml
> +  <RequiredResearchBenchFacilities>Requer</RequiredResearchBenchFacilities>
Não há perda alguma pela remoção.

2022-04-17 20:24 UTC, Kitsune912 commented on Core/Keyed/Misc_Gameplay.xml
> +  <LearningHelper>Auxiliar de Aprend.</LearningHelper>
![image](https://user-images.githubusercontent.com/81825142/163730928-279cf58a-e455-49e1-9d83-e68eb5872e07.png)

2022-04-21 02:47 UTC, LoboMetalurgico approved these changes

2022-04-21 02:47 UTC, merged