[W.I.P.] Correção das Missões do Rotalty
Ludeon/RimWorld-PortugueseBrazilian pull request #244
Opened 2022-04-16 20:33 UTC by Kitsune912

### **📝 Alterações Propostas:**
Apenas corrige os erros das missões do Royalty.

### **📜 Requisitos:**

 - [ ] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [x] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2022-06-28 19:53 UTC, LoboMetalurgico commented
Apenas por curiosidade, o que falta para que este Pull Request fique pronto?

2022-06-29 16:37 UTC, Kitsune912 commented
Estou dando um tapa em todas as missões do _Rotalty_,

Faltam os seguintes arquivos:

- [ ] Script_Hospitality_Refugee.xml
- [ ] Script_Hospitality_Root_Animals.xml
- [ ] Script_Hospitality_Root_Joiners.xml
- [ ] Script_Hospitality_Root_Prisoners.xml
- [ ] Script_ShuttleCrash_Rescue.xml
- [ ] Scripts_ItemPodThreat.xml
- [ ] Scripts_JoinerThreat.xml

2022-06-29 17:38 UTC, LoboMetalurgico commented
Seria possível dar prioridade para aquelas que não exibem nada e as correções gerais serem feitas em outros Pull Requests? Esse bug na tradução vem incomodando os usuários a muito tempo e seria bom corrigir antes fazer um polimento geral.

2022-06-29 19:14 UTC, Kitsune912 commented
Ok!

2022-06-30 15:40 UTC, LoboMetalurgico requested changes

2022-06-30 15:40 UTC, LoboMetalurgico commented on Royalty/DefInjected/QuestScriptDef/Script_Bestower.xml
> +    <li>questDescription->[faction_name] está pronto para conceder [pawn_definite] o título de [newTitle] e o poder de um psínculo nível [psylinkLevel] em uma cerimônia de outorga.\n\nO mestre de cer
```suggestion
    <li>questDescription->[faction_name] está pronto para conceder [pawn_definite] o título de [newTitle] e o poder de um psínculo nível [psylinkLevel] em uma cerimônia de outorga.\n\nO mestre de cerimônias chegará em um transporte e realizará a cerimônia.\n\nO mestre de cerimônias somente dará um título se todos os requisitos da sala do trono forem satisfeitos. Há uma chance de ganhar honra extra, dependendo de quantos espectadores comparecerem à cerimônia. Além disso, cada espectador ganha um bônus de humor.\n\nVocê pode trair o mestre de cerimônias para roubar neuroformadores psínculos, mas isso tornará [faction_name] seu inimigo.\n\nSe você perder ou falhar nesta cerimônia, haverá outras oportunidades mais tarde. Caso o mestre de cerimônias ou os guardas forem agredidos por qualquer razão, haverá consequências diplomáticas.</li>
```

2022-06-30 15:40 UTC, LoboMetalurgico commented on Royalty/DefInjected/QuestScriptDef/Script_BuildMonument_Root_Basic.xml
> +    <li>commonEnding->O tamanho do monumento é [monumentSize] e exigirá estes recursos (valor total [monumentRequiredResourcesMarketValue_money]):\n\n[monumentRequiredResources]\n\nA construção deve
```suggestion
    <li>commonEnding->O tamanho do monumento é [monumentSize] e exigirá estes recursos (valor total [monumentRequiredResourcesMarketValue_money]):\n\n[monumentRequiredResources]\n\nA construção deve ser concluída dentro de [constructionTimeoutTicks_duration] após aceitar a missão. Você receberá as recompensas quando terminar a construção.[dontDestroyMonument]</li>
```

2022-06-30 15:40 UTC, LoboMetalurgico commented on Royalty/DefInjected/QuestScriptDef/Scripts_Utility_Threats.xml
> +    <li>threatDescription->um novo local aparecerá nas proximidades, aonde [allSitePartsDescriptions] Esta ameaça permanecerá até você destruí-la.</li>
```suggestion
    <li>threatDescription->um novo local aparecerá nas proximidades, onde [allSitePartsDescriptions] Esta ameaça permanecerá até você destruí-la.</li>
```

2022-06-30 20:35 UTC, LoboMetalurgico approved these changes

2022-06-30 20:36 UTC, merged