1.4 / Core - Backstories: Adult_Tribal & Child_Tribal
Ludeon/RimWorld-PortugueseBrazilian pull request #272
Opened 2022-11-18 02:19 UTC by Offcolor

Reformulação das Histórias de Fundo que envolvem adultos e crianças tribais

### **📝 Alterações Propostas:**

-Principais Mudanças: a) Fazer com que o gênero das palavras na descrição mudem de acordo com o sexo do peão; b) ajustar descrições que não têm ligação com o texto original; c) reajustar descrições que têm pequenas alterações para uniformizar com a lingua original

-Pontos de Atenção: "treehouse builder" se tronou "Construtor de casas" para não ficar cortado por não caber no campo de informações do peão (Adult_Tribal, linhas 175 e 177)

### **📜 Requisitos:**

 - [x] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [x] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

As demais histórias de fundo estão sendo ajustadas e serão enviadas de acordo com a categoria

Todas as mudanças foram testadas em jogo e qualquer sugestão é bem vinda!

2022-11-18 04:15 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Adult.xml
> +  <LoreKeeper51.baseDesc>[PAWN_nameDef] era um{PAWN_gender ? m : ma} de uma longa linhagem de guardiões da sabedoria em sua tribo. Toda noite ao redor do fogo, [PAWN_pronoun] trasmitiria conhecimento
```suggestion
  <LoreKeeper51.baseDesc>[PAWN_nameDef] era u{PAWN_gender ? m : ma} de uma longa linhagem de guardiões da sabedoria em sua tribo. Toda noite ao redor do fogo, [PAWN_pronoun] trasmitiria conhecimento antigo e sabedoria útil através de histórias.</LoreKeeper51.baseDesc>
```

2022-11-18 04:16 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Adult.xml
> +  <Warrior94.baseDesc>[PAWN_nameDef] foi um{PAWN_gender ? m : ma} guerreiro{PAWN_gender ? o : a} temível, proficiente com muitas armas. [PAWN_pronoun] participou de muitas batalhas.</Warrior94.baseDe
```suggestion
  <Warrior94.baseDesc>[PAWN_nameDef] foi u{PAWN_gender ? m : ma} guerreir{PAWN_gender ? o : a} temível, proficiente com muitas armas. [PAWN_pronoun] participou de muitas batalhas.</Warrior94.baseDesc>
```

2022-11-18 04:31 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Child.xml
> +  <Bully70.baseDesc>[PAWN_nameDef] atormentou outras crianças por diversão. Para mantê-l{pawn_gender ? o : a} ocupad{PAWN_gender ? o : a}, um ancião {pawn_gender ? o : a} designou para uma caçada em
```suggestion
  <Bully70.baseDesc>[PAWN_nameDef] atormentou outras crianças por diversão. Para mantê-l{PAWN_gender ? o : a} ocupad{PAWN_gender ? o : a}, um ancião {PAWN_gender ? o : a} designou para uma caçada em sua tenra idade.</Bully70.baseDesc>
```
Nestas situações o "objeto" o qual é alvo da análise deve ser em maiúsculo

2022-11-18 04:41 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Child.xml
> +  <Scavenger22.titleShort>Caçado de tesouros</Scavenger22.titleShort>
```suggestion
  <Scavenger22.titleShort>Caçador de tesouros</Scavenger22.titleShort>
```

2022-11-18 19:20 UTC, LoboMetalurgico requested changes
Olá, obrigado pela sua contribuição.

Para aprovarmos, por favor, efetue as correções solicitadas pelo The-Geovanni.

2022-11-19 02:56 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Child.xml
> +  <Hideaway7.title>Escondido</Hideaway7.title>
```suggestion
  <Hideaway7.title>Isolado</Hideaway7.title>
```

2022-11-19 02:56 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Child.xml
> +  <Hideaway7.titleShort>Escondido</Hideaway7.titleShort>
```suggestion
  <Hideaway7.titleShort>Isolado</Hideaway7.titleShort>
```

2022-11-19 02:59 UTC, The-Geovanni commented
@MrGeans , apenas verifique uma última correção nas linhas 64 e 65 do arquivo "Tribal_Child.xml". Hideaway pode ser traduzido melhor como "isolado" ao invés de "escondido"

2022-11-19 03:08 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Adult.xml
> +  <Malingerer28.title>Falso doente</Malingerer28.title>
```suggestion
  <Malingerer28.title>Fingidor</Malingerer28.title>
```

2022-11-19 03:08 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Adult.xml
> +  <Malingerer28.titleShort>Falso doente</Malingerer28.titleShort>
```suggestion
  <Malingerer28.titleShort>Fingidor</Malingerer28.titleShort>
```

2022-11-19 03:11 UTC, The-Geovanni commented on Core/DefInjected/BackstoryDef/Tribal_Adult.xml
>    <StewKeeper95.title>Cozinheiro rústico</StewKeeper95.title>
```suggestion
  <StewKeeper95.title>Cozinheiro de sopa</StewKeeper95.title>
```

2022-11-19 22:27 UTC, MrGeans commented
Solicitações de mudança de @The-Geovanni foram aplicadas

2022-11-20 04:25 UTC, merged