Update Backstories.xml
Ludeon/RimWorld-PortugueseBrazilian pull request #280
Opened 2023-03-03 04:21 UTC by joshnorwich

### **📝 Alterações Propostas:**
Remova o espaço em branco do início da descrição de Forester96

### **📜 Requisitos:**

 - [x] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [ ] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**
Não faço parte da equipe de tradução. Esta é uma correção muito pequena. Você não precisa usar esta solicitação pull para o problema 279

2023-09-23 17:57 UTC, lucasew commented
Adiciona alguns reviewers

2023-10-01 13:18 UTC, Covre912 approved these changes

2023-10-01 16:39 UTC, LoboMetalurgico requested changes
Olá, muito obrigado pelo seu Pull Request,

Infelizmente seu Pull Request não pode ser aprovado no momento, isso se deve ao fato de que a tradução está sendo refatorada para a v1.4 em [outra branch](https://github.com/Ludeon/RimWorld-PortugueseBrazilian/tree/1.4). Se puder migrar sua correção para lá e nos auxiliar com os novos `TODO:`, seria muito bom.

2024-03-13 18:57 UTC, LoboMetalurgico commented
Fechando por nenhuma resposta ser dada.

2024-03-13 18:57 UTC, closed without merging