Correção e Tradução de Keys
Ludeon/RimWorld-PortugueseBrazilian pull request #283
Opened 2023-10-01 18:20 UTC by Covre912

### **📝 Alterações Propostas:**

Corrigindo algumas keys e traduzindo outras.

### **📜 Requisitos:**

 - [ ] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [x] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2023-10-01 18:26 UTC, Covre912 commented
Por que está dando conflito aqui??

2023-10-01 19:57 UTC, LoboMetalurgico commented
@Covre912 sua branch não estava atualizada. Vou tentar corrigir por aqui

2023-10-01 20:15 UTC, LoboMetalurgico commented
@Covre912 Por favor, efetue um teste da tradução atualizada. Após isto, me avise para que possa revisar as alterações.

2023-10-01 21:35 UTC, Covre912 commented
Valeu! Testei, tudo certo.

2023-10-08 17:21 UTC, LoboMetalurgico requested changes
Olá, obrigado pelo seu pull request.

Antes de testar in-game, gostaria que revissasse alguns pontos.

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Designators.xml
> +  <DesignatorPaintBuildingDesc>Designe paredes e mobília para serem pintadas com corante de tintória, que você pode cultivar. Apenas algumas construções podem ser pintados.</DesignatorPaintBuildingDe
```suggestion
  <DesignatorPaintBuildingDesc>Designe paredes e mobílias para serem pintadas com corante de tintória, que você pode cultivar. Apenas algumas construções podem ser pintados.</DesignatorPaintBuildingDesc>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Designators.xml
> +  <DesignatorRemovePaintDesc>Remova a pintura das paredes, mobília e pisos.</DesignatorRemovePaintDesc>
```suggestion
  <DesignatorRemovePaintDesc>Remova a pintura das paredes, mobílias e pisos.</DesignatorRemovePaintDesc>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Dialogs_Various.xml
> +  <ColorPastedSuccessfully>Cor atualizada da área de transferência.</ColorPastedSuccessfully>
```suggestion
  <ColorPastedSuccessfully>Cor da área de transferência atualizada.</ColorPastedSuccessfully>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/FloatMenu.xml
> +  <PrisonerInteractedTooRecently>interagido(a) com muito recentemente</PrisonerInteractedTooRecently>
```suggestion
  <PrisonerInteractedTooRecently>interagiu com muito recentemente</PrisonerInteractedTooRecently>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Letters.xml
>    <BirthdayBiologicalAgeInjuries>{0} atingiu a idade biológica de {1}.\n\nInfelizmente, {0} ganhou as seguintes doenças devido ao envelhecimento:\n{2}</BirthdayBiologicalAgeInjuries>
```suggestion
  <BirthdayBiologicalAgeInjuries>{0} atingiu a idade biológica de {1}.\n\nInfelizmente, {0_nameFull} ganhou as seguintes doenças devido ao envelhecimento:\n{2}</BirthdayBiologicalAgeInjuries>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Letters.xml
>    <LetterBladelinkWeaponBonded>{PAWN_labelShort} estabeleceu um vínculo com a personalidade do {WEAPON label Shirt}.\n\nA partir de agora, o {WEAPON_labelShort} se recusará a ser utilizado por qualqu
```suggestion
  <LetterBladelinkWeaponBonded>{PAWN_labelShort} estabeleceu um vínculo com a personalidade do {WEAPON_labelShort}.\n\nA partir de agora, o {WEAPON_labelShort} se recusará a ser utilizado por qualquer pessoa, exceto {PAWN_labelShort}.</LetterBladelinkWeaponBonded>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Menu_Options.xml
> +  <SaveGameDataLocation>Localização dos Salvamentos</SaveGameDataLocation>
```suggestion
  <SaveGameDataLocation>Localização dos Saves</SaveGameDataLocation>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Menu_Options.xml
> +  <SaveGameDataFolder>Pasta dos Salvamentos</SaveGameDataFolder>
```suggestion
  <SaveGameDataFolder>Pasta dos Saves</SaveGameDataFolder>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Menu_Options.xml
> +  <SaveGameDataFolder>Pasta dos Salvamentos</SaveGameDataFolder>
Como já discutido previamente, "saves" é uma palavra amplamente utilizada no mundo dos jogos, tornando essa alteração desnecessária.

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Menu_Options.xml
> +  <SaveGameDataLocation>Localização dos Salvamentos</SaveGameDataLocation>
Como já discutido previamente, "saves" é uma palavra amplamente utilizada no mundo dos jogos, tornando essa alteração desnecessária.

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Menu_Options.xml
> -  <NamesYouWantToSeeSubText>Estes nomes serão mais proposensos a aparecer de maneira aleatória durante o jogo.</NamesYouWantToSeeSubText>
Por que essa linha foi removida?
Se não era mais necessária, por que o texto base ainda existe?

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <DiscardModChanges>As alterações não foram salvas. Você tem certeza que quer continuar?</DiscardModChanges>
```suggestion
  <DiscardModChanges>As alterações não foram salvas. Você tem certeza de que quer continuar?</DiscardModChanges>
```

2023-10-08 17:21 UTC, LoboMetalurgico commented on Core/Keyed/Menus_Main.xml
> +  <SaveLoadList>Salvar/Carregar Kista...</SaveLoadList>
```suggestion
  <SaveLoadList>Salvar/Carregar Lista...</SaveLoadList>
```

2023-10-09 19:37 UTC, Covre912 commented on Core/Keyed/Menu_Options.xml
> -  <NamesYouWantToSeeSubText>Estes nomes serão mais proposensos a aparecer de maneira aleatória durante o jogo.</NamesYouWantToSeeSubText>
Removi sem querer.

2023-10-10 01:37 UTC, LoboMetalurgico commented on Core/Keyed/Letters.xml
>    <LetterBladelinkWeaponBonded>{PAWN_labelShort} estabeleceu um vínculo com a personalidade do {WEAPON label Shirt}.\n\nA partir de agora, o {WEAPON_labelShort} se recusará a ser utilizado por qualqu
@Covre912 acredito que tenha se esquecido dessa

2023-10-12 23:11 UTC, LoboMetalurgico requested changes
Agradeço pelas correções, mas você acidentalmente pulou uma muito importante.

2023-10-12 23:11 UTC, LoboMetalurgico commented on Core/Keyed/Letters.xml
>    <LetterBladelinkWeaponBonded>{PAWN_labelShort} estabeleceu um vínculo com a personalidade do {WEAPON label Shirt}.\n\nA partir de agora, o {WEAPON_labelShort} se recusará a ser utilizado por qualqu
@Covre912 acredito que você tenha esquecido de verificar essa correção.

2023-10-13 14:49 UTC, Covre912 commented
> Agradeço pelas correções, mas você acidentalmente pulou uma muito importante.

Corrigido!

2023-10-14 07:12 UTC, LoboMetalurgico requested changes
Olá, muito obrigado pelas correções.

Após uma análise final, observei mais alguns pontos que me passaram batido inicialmente.

2023-10-14 07:12 UTC, LoboMetalurgico commented on Core/Keyed/Letters.xml
> +  <LetterTextLungRot>{PAWN} ficou doente devido à exposição prolongada ao gás fétido de decomposição (que é liberado por cadáveres em decomposição).\n\nCertifique-se de possuir uma cama médica e um m
A variável {1} está ausente no texto, isso é esperado?

2023-10-14 07:12 UTC, LoboMetalurgico commented on Core/Keyed/Letters.xml
> +  <BirthdayBiologicalAgeInjuries>{0} atingiu a idade biológica de {1}.\n\nInfelizmente, {0_nameFull} ganhou as seguintes doenças devido ao envelhecimento:\n{2}</BirthdayBiologicalAgeInjuries>
```suggestion
  <BirthdayBiologicalAgeInjuries>{0_nameFull} atingiu a idade biológica de {1}.\n\nInfelizmente, {0_nameFull} ganhou as seguintes doenças devido ao envelhecimento:\n{2}</BirthdayBiologicalAgeInjuries>
```

2023-10-19 16:10 UTC, Covre912 commented on Core/Keyed/Letters.xml
> +  <LetterTextLungRot>{PAWN} ficou doente devido à exposição prolongada ao gás fétido de decomposição (que é liberado por cadáveres em decomposição).\n\nCertifique-se de possuir uma cama médica e um m
Eu acho que sim, não lembro de ter alterado essa linha de tradução. Só se foi atualizada em inglês.

2023-10-19 17:52 UTC, LoboMetalurgico commented on Core/Keyed/Letters.xml
> +  <LetterTextLungRot>{PAWN} ficou doente devido à exposição prolongada ao gás fétido de decomposição (que é liberado por cadáveres em decomposição).\n\nCertifique-se de possuir uma cama médica e um m
Entendido

2023-11-06 01:00 UTC, merged