Pasta: ConceptDef/Tutor
Ludeon/RimWorld-PortugueseBrazilian pull request #300
Opened 2024-04-23 22:45 UTC by IssMoW

### **📝 Alterações Propostas:**

Códice de entidades, novas mecânicas
### **📜 Requisitos:**

 - [ ] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [ ] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2024-04-25 16:36 UTC, LoboMetalurgico requested changes
Olá, obrigado pelo seu Pull Request.

A maioria das correções é apenas para que seja mantida a consistência. Recomendo que verifique se algum termo ou expressão já foi traduzido previamente pela pesquisa de termos do VSCode para evitar problemas futuros.

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <AnomalyResearch.label>pesquisas de anomalias</AnomalyResearch.label>
```suggestion
  <AnomalyResearch.label>pesquisas anômalas</AnomalyResearch.label>
```

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <AnomalyResearch.helpText>Você deve avançar na pesquisa de anomalias estudando entidades sobrenaturais.\n\nExistem dois tipos de pesquisas de anomalias: BÁSICAS e AVANÇADAS. Os projetos de pesquisa
```suggestion
  <AnomalyResearch.helpText>Você deve avançar nas pesquisas anômalas estudando entidades sobrenaturais.\n\nExistem dois tipos de pesquisas anômalas: BÁSICAS e AVANÇADAS. Os projetos de pesquisas básicas progridem ao estudar qualquer entidade; projetos avançados progridem apenas ao estudar entidades avançadas.\n\nVocê poderá ter apenas um projeto básico e avançado ativos ao mesmo tempo. Se nenhum projeto avançado estiver ativo, a pesquisa avançada contribuirá para o projeto básico.</AnomalyResearch.helpText>
```

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <CapturingEntities.helpText>Quando uma entidade está derrubada, porém viva, você poderá capturá-la. Para capturar, selecione um colono, clique com o botão direito na entidade e selecione 'Capturar'
```suggestion
  <CapturingEntities.helpText>Enquanto uma entidade estiver nocauteada, porém viva, você poderá capturá-la. Para capturar, selecione um colono, clique com o botão direito na entidade e selecione 'Capturar'. Você precisará de uma plataforma ou local de contenção vazio.\n\nApós a entidade ser trazida para a plataforma de contenção, você poderá estudá-la afim de obter pontos de pesquisas anômalas.\n\nCuide dos ferimentos de uma entidade ferida para garantir que ela sobreviva.</CapturingEntities.helpText>
```

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <ColonyGhouls.helpText>carniçais são humanos distorcidos por bioferrita. São capazes de regenerar ferimentos rapidamente, tornando-os úteis como lutadores corpo a corpo. No entanto, eles são incapa
```suggestion
  <ColonyGhouls.helpText>carniçais são humanos distorcidos por bioferrita. São capazes de regenerar ferimentos rapidamente, tornando-os úteis como lutadores corpo a corpo. No entanto, eles são incapazes de trabalhar.\n\nCarniçais só comem cadáveres e carne crua. Se passarem fome, irão se tornar hostis.</ColonyGhouls.helpText>
```

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <ColonyGhouls.helpText>carniçais são humanos distorcidos por bioferrita. São capazes de regenerar ferimentos rapidamente, tornando-os úteis como lutadores corpo a corpo. No entanto, eles são incapa
Apesar de estar correto, evitamos o uso deste tipo de conjugação por questões ocorridas no passado.

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <EntityCodex.helpText>Use o códice de entidades para acompanhar quais entidades você descobriu.\n\nA descoberta de novas entidades revelará projetos de pesquisa de anomalias ocultas. Assim que enti
```suggestion
  <EntityCodex.helpText>Use o códice de entidades para acompanhar quais entidades você descobriu.\n\nA descoberta de novas entidades revelará projetos de pesquisa anômalas ocultas. Assim que entidades suficientes forem descobertas, você poderá aumentar o nível do monólito do vazio.\n\nAbra o códice de entidades utilizando o ícone de códice no canto inferior direito da tela.</EntityCodex.helpText>
```

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <StudyingEntities.helpText>Colonos designados para o trabalho de 'Estudo das Trevas' ESTUDARÃO diversas entidades, incluindo criaturas e estruturas.\n\nEstude estruturas como o monólito do vazio se
```suggestion
  <StudyingEntities.helpText>Colonos designados para o trabalho de 'Estudo das Trevas' ESTUDARÃO diversas entidades, incluindo criaturas e estruturas.\n\nEstude estruturas como o monólito do vazio selecionando-o e alternando para a opção 'Estudar'. Algumas entidades devem ser capturadas em uma plataforma ou local de contenção antes de serem estudadas.\n\nO estudo avança seus projetos de pesquisa de anômala. Abra a guia 'Pesquisa' e selecione a subguia 'Anomalia' para visualizar os projetos de pesquisa de anomalias.</StudyingEntities.helpText>
```

2024-04-25 16:36 UTC, LoboMetalurgico commented on Anomaly/DefInjected/ConceptDef/Tutor.xml
> +  <SuppressingEntities.helpText>Mesmo em cativeiro, algumas entidades tornam-se mais ativas com o passar do tempo. Se a barra de atividades de uma entidade ficar completamente cheia, ela se tornará e
```suggestion
  <SuppressingEntities.helpText>Mesmo em cativeiro, algumas entidades tornam-se mais ativas com o passar do tempo. Se a barra de atividade de uma entidade ficar completamente cheia, ela se tornará extremamente perigosa.\n\nPara evitar a ativação completa, você deve SUPRIMÍ-LA periodicamente. Guardas suprimirão entidades.</SuppressingEntities.helpText>
```

2024-04-27 01:22 UTC, merged

2024-04-27 13:09 UTC, IssMoW commented
> Olá, obrigado pelo seu Pull Request.
> 
> A maioria das correções é apenas para que seja mantida a consistência. Recomendo que verifique se algum termo ou expressão já foi traduzido previamente pela pesquisa de termos do VSCode para evitar problemas futuros.

Obrigado pelo feedback