(Aguardando) CreepJoinerBase
Ludeon/RimWorld-PortugueseBrazilian pull request #303
Opened 2024-04-24 02:08 UTC by IssMoW

### **📝 Alterações Propostas:**

Ações de personagens

### **📜 Requisitos:**

 - [ ] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [ ] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2024-04-24 02:40 UTC, Covre912 requested changes
qualquer dúvida só chamar,

alguns pontos recorrentes: 
- mantenha a capitalização inicial (a não ser que você saiba o que está fazendo) 
- não tem pq usar o {PAWN_possessive}, no português o pronome possessivo se refere ao objeto não ao sujeito
- próclise e ênclise não são estilísticas
- de preferência, tente manter títulos como substantivos (existem excessões)

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
> +  <HellcatBurner.label>Rifle gato infernal</HellcatBurner.label>
```suggestion
  <HellcatBurner.label>lança-chamas infernal</HellcatBurner.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
> +  <IncineratorBurner.label>Incinerador escaldante</IncineratorBurner.label>
```suggestion
  <IncineratorBurner.label>incinerador escaldante</IncineratorBurner.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
> +  <HellcatBurner.description>Gaste uma carga pressurizada de bioferrita para criar uma explosão de chamas.</HellcatBurner.description>
```suggestion
  <HellcatBurner.description>Gaste uma carga de bioferrita pressurizada para criar uma explosão de chamas.</HellcatBurner.description>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
> +  <IncineratorBurner.description>Gaste uma carga pressurizada de bioferrita para criar um enorme cone de chama.</IncineratorBurner.description>
```suggestion
  <IncineratorBurner.description>Gaste uma carga de bioferrita pressurizada para criar um enorme cone de chama.</IncineratorBurner.description>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
> +  <Assault.message>{PAWN_nameDef} tornou-se hostil!</Assault.message>
```suggestion
  <Assault.message>{PAWN_nameDef} se tornou hostil!</Assault.message>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
> +  <FleshbeastEmergence.label>surgimento de besta carnal</FleshbeastEmergence.label>
```suggestion
  <FleshbeastEmergence.label>carnalização</FleshbeastEmergence.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
> +  <FleshbeastEmergence.letterLabel>{PAWN_nameDef} transformou-se</FleshbeastEmergence.letterLabel>
```suggestion
  <FleshbeastEmergence.letterLabel>{PAWN_nameDef} se transformou!</FleshbeastEmergence.letterLabel>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
> +  <SightstealerAttack.label>ladrão de olhos ataque</SightstealerAttack.label>
```suggestion
  <SightstealerAttack.label>ataque espectral</SightstealerAttack.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
> +  <SightstealerAttack.letterDesc>{PAWN_nameDef} soltou um grito metade humano meio distorcido.\n\nVocê consegue ouvir outros gritos à distância atendendo ao chamado.\n\nEles estão vindo...</Sightstea
```suggestion
  <SightstealerAttack.letterDesc>{PAWN_nameDef} soltou um distorcido grito inumano.\n\nVocê consegue ouvir outros gritos à distância atendendo ao chamado.\n\nEles estão vindo...</SightstealerAttack.letterDesc>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
> +  <SightstealerAttack.letterLabel>O uivo de {PAWN_nameDef}</SightstealerAttack.letterLabel>
```suggestion
  <SightstealerAttack.letterLabel>uivo de {PAWN_nameDef}</SightstealerAttack.letterLabel>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Aggressive.xml
> +  <Assault.label>assalto básico</Assault.label>
```suggestion
  <Assault.label>hostilização</Assault.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <Alchemist.letterExtra>{PAWN_nameDef} afirma ter amplo conhecimento da prática alquímica. {PAWN_pronoun} pode, usando influência arquetecnológica desconhecida, transmutar aço em vários recursos val
```suggestion
  <Alchemist.letterExtra>{PAWN_nameDef} afirma possuir amplo conhecimento da prática alquímica. {PAWN_pronoun} pode, usando influência arquotecnológica desconhecida, transmutar aço em recursos valiosos.</Alchemist.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <BodyMastery.letterExtra>Os olhos de {PAWN_nameDef} são de um branco incomum. Utilizando do conhecimento popular local, {PAWN_pronoun} dominou {PAWN_possessive} ritmos metabólicos e circadianos. Pe
```suggestion
  <BodyMastery.letterExtra>Os olhos de {PAWN_nameDef} são de um branco incomum. Utilizando-se do conhecimento popular local, {PAWN_pronoun} dominou seus ritmos metabólicos e circadianos. Pelo menos é isso que {PAWN_pronoun} afirma. {PAWN_nameDef} nunca dorme e nem precisa comer, embora os seus olhos expressem uma fome primitiva.</BodyMastery.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <DeathRefusal.label>recusa da morte</DeathRefusal.label>
```suggestion
  <DeathRefusal.label>licença mortal</DeathRefusal.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <DeathRefusal.letterExtra>Como antigo membro de um ritual cultista, {PAWN_nameDef} tem a habilidade de desafiar a morte. A arquetecnologia sombria percorre todo o corpo de {PAWN_possessive}, permit
```suggestion
  <DeathRefusal.letterExtra>Como decano(a) de um ritual cultista, {PAWN_nameDef} possui a habilidade de desafiar a morte. A arquotecnologia sombria percorre todo o seu corpo, permitindo que {PAWN_pronoun} se auto-ressuscite. Quando {PAWN_pronoun} faz isso, o seu corpo se reforma rapidamente, substituindo órgãos perdidos e curando feridas. O processo é, no entanto, imperfeito.</DeathRefusal.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <Fleshcrafter.letterExtra>{PAWN_nameDef} afirma ser dotado da arte sombria de reanimar carne morta. {PAWN_pronoun} pode transformar cadáveres em horríveis bestas carnais.</Fleshcrafter.letterExtra>
```suggestion
  <Fleshcrafter.letterExtra>{PAWN_nameDef} afirma ser dotado(a) da arte sombria de reanimar carne. {PAWN_pronoun} pode transformar cadáveres em horríveis bestas carnais.</Fleshcrafter.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <Joybringer.label>portador de alegria</Joybringer.label>
```suggestion
  <Joybringer.label>porta-alegria</Joybringer.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <Joybringer.letterExtra>{PAWN_nameDef} é um portador de alegria e serenidade cujas habilidades vão além do mero carisma. {PAWN_pronoun} levanta o ânimo e inspira outros contando piadas e espalhando
```suggestion
  <Joybringer.letterExtra>{PAWN_nameDef},  cujas habilidades vão além do mero carisma, é um(a) portador(a) de alegria e de serenidade. {PAWN_pronoun} levanta o ânimo e inspira outros contando piadas e espalhando pensamentos felizes.</Joybringer.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <Occultist.letterExtra>{PAWN_pronoun} conhece profundamente todas as coisas relacionadas ao vazio. {PAWN_pronoun} pode estudar fenômenos sobrenaturais mais rápido que outros {PAWN_pronoun} também o
```suggestion
  <Occultist.letterExtra>{PAWN_pronoun} conhece profundamente todas as coisas relacionadas ao vazio. {PAWN_pronoun} pode estudar fenômenos sobrenaturais mais rápido que outros. {PAWN_pronoun} também os ensinará quando tiver oportunidade.</Occultist.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <PerfectHuman.letterExtra>{PAWN_nameDef} é habilidoso em tudo em um grau não natural. Independentemente do assunto, {PAWN_pronoun} domina-o. Além disso, a ética de trabalho de {PAWN_possessive} é n
```suggestion
  <PerfectHuman.letterExtra>{PAWN_nameDef} parece ser habilidoso(a) em tudo, em um grau não natural. Independentemente do assunto, {PAWN_pronoun} o domina. Além disso, a sua ética de trabalho é notável. {PAWN_pronoun} parece ser o(a) operário(a) perfeito(a).</PerfectHuman.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <PsychicButcher.letterExtra>Os animais ficam nervosos perto de {PAWN_nameDef}. {PAWN_pronoun} tem o poder não natural de deformar a carne de criaturas vivas, fazendo-as explodir em pilhas de carne
```suggestion
  <PsychicButcher.letterExtra>Os animais ficam nervosos perto de {PAWN_nameDef}. {PAWN_pronoun} tem o poder sobrenatural de deformar a carne de criaturas vivas, fazendo-as explodir em pilhas de carne retorcida. {PAWN_nameDef} afirma usar o seu dom exclusivamente para abater animais, mas está claro que {PAWN_pronoun} poderia facilmente abater uma pessoa.</PsychicButcher.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <ShamblerOverlord.label>senhor morto-vivo</ShamblerOverlord.label>
```suggestion
  <ShamblerOverlord.label>propietário trôpego</ShamblerOverlord.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <ShamblerOverlord.letterExtra>O corpo de {PAWN_nameDef} está repleto de arquitas corruptas. {PAWN_pronoun} pode liberá-las à vontade, criando uma névoa morta capaz de reanimar cadáveres próximos.</
```suggestion
  <ShamblerOverlord.letterExtra>O corpo de {PAWN_nameDef} está repleto de arquitas corrompidas. {PAWN_pronoun} pode liberá-las à vontade, criando uma névoa mortal capaz de reanimar cadáveres próximos.</ShamblerOverlord.letterExtra>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <UnnaturalHealing.label>cura não natural</UnnaturalHealing.label>
```suggestion
  <UnnaturalHealing.label>cura sobrenatural</UnnaturalHealing.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <UnnaturalHealing.letterExtra>{PAWN_pronoun} se oferece para usar o poder de cura de {PAWN_possessive} para lhe ajudar.</UnnaturalHealing.letterExtra>
```suggestion
  <UnnaturalHealing.letterExtra>{PAWN_pronoun} se oferece para usar seu poder de cura para o(a) ajudar.</UnnaturalHealing.letterExtra>
```
"lhe" é pronome de quando tem preposição

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Aggressive.label>agressivo</Aggressive.label>
```suggestion
  <Aggressive.label>agressividade</Aggressive.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Aggressive.letterDesc>O comportamento de {PAWN_nameDef} mudou repentinamente. Um sorriso ameaçador divide o rosto de {PAWN_possessive}.\n\n{PAWN_nameDef} tornou-se hostil.</Aggressive.letterDesc>
```suggestion
  <Aggressive.letterDesc>O comportamento de {PAWN_nameDef} mudou repentinamente. Um sorriso ameaçador divide o seu rosto.\n\n{PAWN_nameDef} se tornou hostil.</Aggressive.letterDesc>
```
próclise e ênclise não são estilísticos, ênclise é só no início de oração

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Aggressive.letterLabel>hostil/Aggressive.letterLabel>
```suggestion
  <Aggressive.letterLabel>hostilidade de {PAWN_nameDef}/Aggressive.letterLabel>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Disturbing.label>perturbado</Disturbing.label>
```suggestion
  <Disturbing.label>perturbação</Disturbing.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <EntityJailbreaker.label>fuga de entidade</EntityJailbreaker.label>
```suggestion
  <EntityJailbreaker.label>fuga de entidades</EntityJailbreaker.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Leaves.label>partiu</Leaves.label>
```suggestion
  <Leaves.label>partida</Leaves.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Leaves.letterDesc>{PAWN_nameDef} agradece sua hospitalidade, mas diz que é hora de {PAWN_objective} seguir em frente.</Leaves.letterDesc>
```suggestion
  <Leaves.letterDesc>{PAWN_nameDef} agradece sua hospitalidade, mas diz que é hora de seguir em frente.</Leaves.letterDesc>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Leaves.letterLabel>Partida de {PAWN_nameDef}</Leaves.letterLabel>
```suggestion
  <Leaves.letterLabel>partida de {PAWN_nameDef}</Leaves.letterLabel>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <Metalhorror.label>Horror Metálico</Metalhorror.label>
```suggestion
  <Metalhorror.label>horror metálico</Metalhorror.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <OrganDecay.label>decadência de órgãos</OrganDecay.label>
```suggestion
  <OrganDecay.label>deterioração de órgãos</OrganDecay.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Downsides.xml
> +  <PsychicAgony.letterDesc>{PAWN_nameDef} involuntariamente lançou um pulso de agonia psíquica! {PAWN_pronoun} tentou evitar, mas não conseguiu.\n\nCriaturas próximas sentirão uma intensa dor . Os ef
```suggestion
  <PsychicAgony.letterDesc>{PAWN_nameDef} involuntariamente lançou um pulso agoniante! {PAWN_pronoun} tentou evitar, mas não conseguiu.\n\nCriaturas próximas sentirão uma intensa dor. Os efeitos durarão vários dias.</PsychicAgony.letterDesc>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.label>agressivo</AggressiveRejection.label>
```suggestion
  <AggressiveRejection.label>agressividade</AggressiveRejection.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.letterDesc>Ao ser rejeitado, {PAWN_nameDef} ficou furioso e começou a atacar com raiva assassina!</AggressiveRejection.letterDesc>
```suggestion
  <AggressiveRejection.letterDesc>Ao ser rejeitado(a), {PAWN_nameDef} ficou furioso(a) e entrou em um frenesi assassino!</AggressiveRejection.letterDesc>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.letterLabel>{PAWN_nameDef} hostil</AggressiveRejection.letterLabel>
```suggestion
  <AggressiveRejection.letterLabel>hostilidade de {PAWN_nameDef}</AggressiveRejection.letterLabel>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <Departure.label>partiu</Departure.label>
```suggestion
  <Departure.label>partida</Departure.label>
```

2024-04-24 02:40 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <Departure.letterDesc>{PAWN_nameDef} está desapontado em como você tratou {PAWN_objective}. {PAWN_pronoun} decidiu ir embora.</Departure.letterDesc>
```suggestion
  <Departure.letterDesc>{PAWN_nameDef} está desapontado(a) em como você {PAWN_objective} tratou. {PAWN_pronoun} decidiu ir embora.</Departure.letterDesc>
```

2024-04-24 02:45 UTC, IssMoW commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.label>agressivo</AggressiveRejection.label>
agressividade-} aggressiveness? ao que parece o contexto se refere a uma rejeição agressiva

2024-04-24 02:48 UTC, IssMoW commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.letterDesc>Ao ser rejeitado, {PAWN_nameDef} ficou furioso e começou a atacar com raiva assassina!</AggressiveRejection.letterDesc>
tem tesão no frenesi? kkkk o texto base ja utiliza demais a expressão frenesi se usar onde não está na tradução base vai se tornar uma palavra altamente enfadonha.

2024-04-24 16:08 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.label>agressivo</AggressiveRejection.label>
justamente, ao invés de aparecer uma carta ou sla escrito: "agressivo", aparece uma "agressividade", que é neutro

agressividade não passa do substantivo de agressivo

2024-04-24 16:11 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.letterDesc>Ao ser rejeitado, {PAWN_nameDef} ficou furioso e começou a atacar com raiva assassina!</AggressiveRejection.letterDesc>
eu tinha colocado pra estilizar um pouco, o termo traduzido do colapso mental "murderous rage" é raiva assassina. mas realmente é um termo que aparece bastante kk

2024-04-28 15:01 UTC, Covre912 requested changes

2024-04-28 15:01 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Rejections.xml
> +  <AggressiveRejection.label>agressivo</AggressiveRejection.label>
O título de uma carta.

2024-04-28 15:01 UTC, Covre912 commented on Anomaly/DefInjected/AbilityDef/Weapons_Ranged.xml
> +  <IncineratorBurner.label>Incinerador escaldante</IncineratorBurner.label>
Não marque como resolvido revisões sem antes comentar o porquê.

2024-07-01 18:17 UTC, Covre912 requested changes

2024-07-01 18:17 UTC, Covre912 commented on Anomaly/DefInjected/CreepJoinerBaseDef/Benefits.xml
> +  <BodyMastery.label>domínio sobre o corpo</BodyMastery.label>
```suggestion
  <BodyMastery.label>domínio corporal</BodyMastery.label>
```

2024-07-30 16:48 UTC, LoboMetalurgico approved these changes
Obrigado!

2024-07-30 16:48 UTC, merged