(Aguardando) Pastas: Entitycodex e GameCondition
Ludeon/RimWorld-PortugueseBrazilian pull request #304
Opened 2024-04-24 11:50 UTC by IssMoW

### **📝 Alterações Propostas:**

Descrições de eventos e criaturas anomaly.

### **📜 Requisitos:**

 - [ ] Você testou as traduções antes de publicar o pull request?
 - [x] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x] Você verificou se sua fork e sua branch estão atualizadas?
 - [ ] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2024-04-24 16:30 UTC, Covre912 requested changes
depois vamos mudar todas as instâncias de chuva sanguínea para chuva de sangue

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Deathpall.description>Uma névoa cinza-cadáver composta por arquites microscópicas autoalimentados criados por alguma superinteligência desconhecida. Quando pousam sobre carne morta, elas penetram
```suggestion
  <Deathpall.description>Uma névoa cinza-cadáver composta por arquitas microscópicas autoalimentados criadas por alguma superinteligência desconhecida. Quando pousam sobre carne morta, penetram o cadáver e reanimam-no para criar uma imitação trôpega dos vivos.</Deathpall.description>
```
archite -> arquita

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <FleshmassNucleus.label>núcleo de massa carnal</FleshmassNucleus.label>
```suggestion
  <FleshmassNucleus.label>núcleo carnal</FleshmassNucleus.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Ghoul.description>Uma pessoa implantada com um fragmento arquetecnologico distorcida por influências psíquicas sombrias em uma máquina assassina.</Ghoul.description>
```suggestion
  <Ghoul.description>Uma pessoa implantada com um fragmento arquotecnológico distorcido por influências psíquicas sombrias em uma máquina assassina.</Ghoul.description>
```
archotech -> arquotecnológico (adjetivo) ou arquotécnico (substantivo)

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <GoldenCube.label>cubo dourado</GoldenCube.label>
```suggestion
  <GoldenCube.label>cubo de ouro</GoldenCube.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Noctol.label>noctol</Noctol.label>
```suggestion
  <Noctol.label>coturno</Noctol.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <PitGate.label>entrada do abismo</PitGate.label>
```suggestion
  <PitGate.label>portal do abismo</PitGate.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Shambler.label>morto-vivo</Shambler.label>
```suggestion
  <Shambler.label>trôpego</Shambler.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Shambler.description>Cadáveres reanimados por arquites microscópicas. mortos-vivos são lentos, estúpidos e atacam implacavelmente. Se não forem capturados morrem de exaustão metábolica após alguns
```suggestion
  <Shambler.description>Cadáveres reanimados por arquitas microscópicas. Trôpegos são lentos, estúpidos e atacam implacavelmente. Se não forem capturados, morrem de exaustão metabólica após alguns dias.</Shambler.description>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Sightstealer.label>ladrão de olhos</Sightstealer.label>
```suggestion
  <Sightstealer.label>espectral</Sightstealer.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <TwistedObelisk.label>obelisco torcido</TwistedObelisk.label>
```suggestion
  <TwistedObelisk.label>obelisco retorcido</TwistedObelisk.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <UnnaturalCorpse.label>corpo não natural</UnnaturalCorpse.label>
```suggestion
  <UnnaturalCorpse.label>cadáver sobrenatural</UnnaturalCorpse.label>
```
corspe -> cadáver

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <UnnaturalCorpse.description>Um cadáver estranho que parece ceroso e quente ao toque. Há algo profundamente perturbador nisso.</UnnaturalCorpse.description>
```suggestion
  <UnnaturalCorpse.description>Um cadáver estranho que parece ceroso e quente ao toque. É algo profundamente perturbador.</UnnaturalCorpse.description>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.label>chuva de sangue</BloodRain.label>
```suggestion
  <BloodRain.label>chuva sanguínea</BloodRain.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.description>Um fluido sobrenatural semelhante a sangue está chovendo. Qualquer um que sair de casa por muito tempo entrará em um frenesi de fúria.</BloodRain.description>
```suggestion
  <BloodRain.description>Um psicofluido sobrenatural semelhante a sangue está caindo do céu. A curta exposição à precipitação orgânica acarreta em fúrias descontroladas.</BloodRain.description>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.endMessage>A chuva de sangue está terminando.</BloodRain.endMessage>
```suggestion
  <BloodRain.endMessage>A chuva sanguínea está terminando.</BloodRain.endMessage>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.letterText>Gotas de um fluido espesso semelhante a sangue começaram a cair do céu.\n\nQualquer pessoa exposta sente uma raiva crescente que fortalece os ataques corpo a corpo, mas eventu
```suggestion
  <BloodRain.letterText>Gotas de um fluido espesso semelhante a sangue começaram a cair do céu.\n\nA curta exposição à precipitação orgânica acarreta em fúrias descontroladas. A intensidade do efeito varia entre os indivíduos, dependendo de suas características, de suas sensibilidades psíquicas e de seus fatores individuais aleatórios.</BloodRain.letterText>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <DeathPall.description>Uma nuvem cinza-morte desceu sobre a área.\n\nA nuvem é feita de arquitas microscópicas autoalimentadas, criadas por alguma superinteligência desconhecida. Quando pousarem em
```suggestion
  <DeathPall.description>Uma nuvem cinza-morte ruiu sobre a área.\n\nA nuvem é feita de arquitas microscópicas autoalimentadas, criadas por alguma superinteligência desconhecida. Quando pousarem sobre carne morta, entrarão no corpo e o reanimarão como uma imitação distorcida da vida.\n\nOs mortos ressuscitarão! Queime, enterre, destrua ou mova cadáveres para dentro de casa para evitar que ressuscitem.</DeathPall.description>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <DeathPall.letterText>Uma nuvem cinza-morte desceu sobre a área.\n\nA nuvem é feita de arquitas microscópicas autoalimentadas, criadas por alguma superinteligência desconhecida. Quando pousarem em
```suggestion
  <DeathPall.letterText>Uma nuvem cinza-morte ruiu sobre a área.\n\nA nuvem é feita de arquitas microscópicas autoalimentadas, criadas por alguma superinteligência desconhecida. Quando pousarem sobre carne morta, entrarão no corpo e o reanimarão como uma imitação distorcida da vida.\n\nOs mortos ressuscitarão! Queime, enterre, destrua ou mova cadáveres para dentro de casa para evitar que ressuscitem.</DeathPall.letterText>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <GrayPall.description>Neblina densa está cobrindo a área. Tem um cheiro antigo e arde na pele. O cinza não natural invoca uma sensação de pavor.</GrayPall.description>
```suggestion
  <GrayPall.description>Uma neblina densa está cobrindo a área. Um cheiro ancestral é emanado e a pele sofre ardências com o contato. O cinza sobrenatural invoca uma sensação de pavor.</GrayPall.description>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <GrayPall.letterText>Neblina densa está cobrindo a área. Tem um cheiro antigo e arde na pele. O cinza não natural invoca uma sensação de pavor.</GrayPall.letterText>
```suggestion
  <GrayPall.letterText>Uma neblina densa está cobrindo a área. Um cheiro ancestral é emanado e a pele sofre ardências com o contato. O cinza sobrenatural invoca uma sensação de pavor.</GrayPall.letterText>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <HateChantDrone.label>Cântico de ódio</HateChantDrone.label>
```suggestion
  <HateChantDrone.label>cântico de ódio</HateChantDrone.label>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <HateChantDrone.description>Os cultistas de Horax estão cantando um canto psiquicamente sintonizado. O canto sinistro transmite um ódio sombrio e onírico. Faz sua cabeça latejar e sua pele arrepiar
```suggestion
  <HateChantDrone.description>Os cultistas Horaxianos estão cantando um canto psiquicamente sintonizado. O canto sinistro transmite um ódio sombrio e onírico. Sua cabeça lateja e sua pele se arrepia. Enquanto a melodia continuar, seus colonos ficarão infelizes.\n\nO canto continuará a ficar mais intenso se os cultistas não forem detidos.</HateChantDrone.description>
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  mortais
```suggestion
```

2024-04-24 16:30 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <UnnaturalDarkness.description>O mundo está coberto por uma camada de escuridão sobrenatural. Da escuridão, pode-se ouvir o gemido inumano de criaturas . Fique na luz.</UnnaturalDarkness.descriptio
```suggestion
  <UnnaturalDarkness.description>O mundo está coberto por uma camada de escuridão sobrenatural. Da escuridão, pode-se ouvir o gemido inumano de criaturas. Permaneça na luz.</UnnaturalDarkness.description>
```

2024-04-27 23:33 UTC, LoboMetalurgico commented
Você acabou de se auto revisar? @IssMoW

2024-04-27 23:37 UTC, IssMoW commented
> Você acabou de se auto revisar? @IssMoW

Então mamei, achei que funcionária da mesma forma mas que apenas outro revisor poderia dar commit. Vou deletar as revisões e criar comentário kkkkkk

2024-04-27 23:46 UTC, IssMoW commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <BloodRain.description>Um psicofluido espesso semelhante ao sangue que cai do céu. Qualquer pessoa exposta a isso sente um ódio crescente que eventualmente se tornará uma fúria irracional.</BloodRa
Um psicofluido espesso semelhante ao sangue que cai do céu. Qualquer um exposto a isso sente um ódio crescente que eventualmente se transformará em uma fúria descontrolada.

2024-04-27 23:46 UTC, IssMoW commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Sightstealer.label>ladrão de olhos</Sightstealer.label>
Espreitador

2024-04-27 23:46 UTC, IssMoW commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <UnnaturalCorpse.label>corpo não natural</UnnaturalCorpse.label>
Cadáver anormal

2024-04-27 23:46 UTC, IssMoW commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.description>Um fluido sobrenatural semelhante a sangue está chovendo. Qualquer um que sair de casa por muito tempo entrará em um frenesi de fúria.</BloodRain.description>
Um fluido sobrenatural semelhante a sangue está chovendo. Qualquer um que ficar fora de casa por muito tempo entrará em um frenesi de fúria descontrolada.

2024-04-27 23:46 UTC, IssMoW commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <GrayPall.description>Neblina densa está cobrindo a área. Tem um cheiro antigo e arde na pele. O cinza não natural invoca uma sensação de pavor.</GrayPall.description>
Uma neblina densa está cobrindo a área. Um cheiro ancestral é emanado e a pele arde com o contato. O cinza sobrenatural invoca uma sensação de

2024-04-27 23:47 UTC, IssMoW commented
> Você acabou de se auto revisar? @IssMoW

Pronto @LoboMetalurgico

2024-04-27 23:54 UTC, LoboMetalurgico commented
Ainda existem reviews em aberto. Verifique as reviews do covre e se não concordar com alguma, comente NELA o motivo.

2024-04-28 00:27 UTC, IssMoW commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <DeathPall.description>Uma nuvem cinza-morte desceu sobre a área.\n\nA nuvem é feita de arquitas microscópicas autoalimentadas, criadas por alguma superinteligência desconhecida. Quando pousarem em
Expressão ruir é estranha. Arroz e feijão... Ou outro sinônimo

2024-04-28 00:27 UTC, IssMoW commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <GrayPall.letterText>Neblina densa está cobrindo a área. Tem um cheiro antigo e arde na pele. O cinza não natural invoca uma sensação de pavor.</GrayPall.letterText>
Uma neblina densa está cobrindo a área. Um cheiro ancestral é emanado e a pele arde com o contato. O cinza sobrenatural invoca uma sensação de pavor.

2024-04-28 00:30 UTC, IssMoW commented
> Ainda existem reviews em aberto. Verifique as reviews do covre e se não concordar com alguma, comente NELA o motivo.

@LoboMetalurgico pronto creio que agora eu tenha feito do modo correto.

2024-04-28 15:11 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <BloodRain.description>Um psicofluido espesso semelhante ao sangue que cai do céu. Qualquer pessoa exposta a isso sente um ódio crescente que eventualmente se tornará uma fúria irracional.</BloodRa
Erro meu, traduzi errado colocando orgânica como acessório de precipitação.

A "curta" ali não muda nada. Pela descrição, "qualquer um exposto sente", implica que é categoricamente impossível não sentir, eventualmente (e é aqui que de fato foi omitido, coloquei lá na sugestão), raivas malucas uma vez que exposto.

2024-04-28 15:12 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <GrayPall.letterText>Neblina densa está cobrindo a área. Tem um cheiro antigo e arde na pele. O cinza não natural invoca uma sensação de pavor.</GrayPall.letterText>
👍

2024-04-28 15:18 UTC, Covre912 requested changes

2024-04-28 15:18 UTC, Covre912 commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <GrayPall.description>Neblina densa está cobrindo a área. Tem um cheiro antigo e arde na pele. O cinza não natural invoca uma sensação de pavor.</GrayPall.description>
👍

2024-04-28 17:31 UTC, LoboMetalurgico commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.description>Um fluido sobrenatural semelhante a sangue está chovendo. Qualquer um que sair de casa por muito tempo entrará em um frenesi de fúria.</BloodRain.description>
Estou de acordo com a sugestão do covre.

2024-04-28 17:32 UTC, LoboMetalurgico commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <UnnaturalCorpse.label>corpo não natural</UnnaturalCorpse.label>
Estou de acordo com a sugestão do Covre.

2024-04-28 17:33 UTC, LoboMetalurgico commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <GoldenCube.label>cubo dourado</GoldenCube.label>
@Covre912 seria isso uma questão de consistência? Do contrário, creio que cubo dourado seja melhor.

2024-04-29 09:57 UTC, LoboMetalurgico approved these changes
Acredito que esteja tudo certo agora.

2024-04-29 11:28 UTC, IssMoW reviewed
Pequena dúvida

2024-04-29 11:28 UTC, IssMoW commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.letterText>Gotas de um fluido espesso semelhante a sangue começaram a cair do céu.\n\nA curta exposição à precipitação orgânica acarreta em fúrias descontroladas. A intensidade do efeito
@LoboMetalurgico uma dúvida, o commits foi marcado como "consistência" há de ter consistência mesmo quando o texto base falta com ela? Por exemplo o commit em questão explicava algumas possibilidades que não existem mais no traduzido.

2024-04-29 17:15 UTC, LoboMetalurgico commented on Anomaly/DefInjected/GameConditionDef/GameConditions_Misc.xml
> +  <BloodRain.letterText>Gotas de um fluido espesso semelhante a sangue começaram a cair do céu.\n\nA curta exposição à precipitação orgânica acarreta em fúrias descontroladas. A intensidade do efeito
É possível manter a consistência e ainda assim, corrigir o texto. Exemplo: 

```suggestion
  <BloodRain.letterText>Gotas de um fluido espesso semelhante a sangue começaram a cair do céu.\n\nA curta exposição à precipitação orgânica acarreta em fúrias descontroladas, o que fortalace o ataque corpo a corpo, mas eventualmente se tornará algo irracional. Os animais expostos se tornarão caçadores de humanos. A intensidade do efeito varia entre os indivíduos, dependendo de suas características, de suas sensibilidades psíquicas e de seus fatores individuais aleatórios.</BloodRain.letterText>
```

2024-07-01 18:19 UTC, Covre912 requested changes

2024-07-01 18:19 UTC, Covre912 commented on Anomaly/DefInjected/EntityCodexEntryDef/EntityCodexEntryDefs.xml
> +  <Deathpall.description>Uma névoa cinza-cadáver composta por arquitas microscópicas autoalimentados criadas por alguma superinteligência desconhecida. Quando pousam sobre carne morta, penetram o cad
```suggestion
  <Deathpall.description>Uma névoa cinza-cadáver composta por arquitas microscópicas auto-alimentados criadas por alguma superinteligência desconhecida. Quando pousam sobre carne morta, penetram o cadáver e reanimam-no para criar uma imitação trôpega dos vivos.</Deathpall.description>
```

2024-07-30 16:49 UTC, LoboMetalurgico approved these changes
Muito Obrigado!

2024-07-30 16:49 UTC, merged