Feat/anomaly
Ludeon/RimWorld-PortugueseBrazilian pull request #307
Opened 2024-04-25 01:07 UTC by Froxynox

### **📝 Alterações Propostas:** Anomaly/ tradução da pasta PsychicRituals

### **📜 Requisitos:**

 - [ ] Você testou as traduções antes de publicar o pull request?
 - [x ] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [x ] Você verificou se sua fork e sua branch estão atualizadas?
 - [ ] Você já faz parte da equipe de tradução?

### **💬 Comentários Adicionais:**

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <Brainwipe.description>Apaga as memórias da pessoa. Eventos traumaticos serão esquecidos. Prisioneiros irão esquecer de suas submissões, sendo mais fácil de recrutar, mesmo se ele estava inebálavel
```suggestion
  <Brainwipe.description>Apaga as memórias da pessoa. Eventos traumáticos serão esquecidos. Prisioneiros irão esquecer de sua lealmente, sendo mais fáceis de recrutar, mesmo que anteriormente fossem inabaláveis. indivíduos desumanizados irão esquecer suas conexões com o vazio. Infelizmente, os efeitos perturbadores do ritual irá induzir a um coma que deverá durar por um longo tempo, especialmente se a qualidade do ritual for pobre.</Brainwipe.description>
```

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <Brainwipe.outcomeDescription>O alvo terá uma limpeza cerebral.\n\nCom a atual qualidade do ritual, o alvo também irá entrar em um coma por {0}.</Brainwipe.outcomeDescription>
```suggestion
  <Brainwipe.outcomeDescription>O alvo sofrerá uma limpeza cerebral.\n\nCom a atual qualidade ritual, o alvo irá entrar em um coma por {0}.</Brainwipe.outcomeDescription>
```

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <Chronophagy.description>Induz uma distante arquetecnologia para transferir entropia de uma pessoa para outra. Isso causa que o alvo irá envelhecer rapidamente enquanto o invocador se torna jovem,
```suggestion
  <Chronophagy.description>Induz uma distante arquotecnologia a transferir entropia de uma pessoa para outra. Isso fará com que o alvo  envelheça rapidamente enquanto o invocador se torna jovem, potencializando a cura de cicatrizes ou doenças relacionadas a velhice. O alvo irá sofrer dano cerebral, causando um coma de muitos dias.</Chronophagy.description>
```

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <Chronophagy.outcomeDescription>Na atual qualidade do ritual, o invocador ficará {0} anos mais novo e o alvo ficará {1} anos mais velho.\n\nO alvo sofrerá de dano cerebral e cairá em uma coma.</Chr
```suggestion
  <Chronophagy.outcomeDescription>Na atual qualidade do ritual, o invocador ficará {0} anos mais novo e o alvo ficará {1} anos mais velho.\n\nO alvo sofrerá dano cerebral e entrará em coma.</Chronophagy.outcomeDescription>
```

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <ImbueDeathRefusal.label>imbuir recusa de morte</ImbueDeathRefusal.label>
```suggestion
  <ImbueDeathRefusal.label>imbuir licença mortal</ImbueDeathRefusal.label>
```

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <ImbueDeathRefusal.description>Linkar o alvo com uma distante motor arquetecnológico que consegue trazer eles de volta da morte em segundos. Esse processo não está livre de efeitos colaterais.</Imb
```suggestion
  <ImbueDeathRefusal.description>Conecte o alvo a um distante motor arquotecnológico capaz de trazer mortos de volta a vida em segundos. Esse processo não está livre de danos colaterais.</ImbueDeathRefusal.description>
```

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <ImbueDeathRefusal.outcomeDescription>O alvo ganhará recusa de morte.\n\nCom a atual qualidade, todas as habilidades dos alvos também serão reduzidas para {0}.</ImbueDeathRefusal.outcomeDescription
```suggestion
  <ImbueDeathRefusal.outcomeDescription>O alvo receberá licença mortal.\n\nCom a atual qualidade, todas as habilidades dessa pessoa será reduzida para {0}.</ImbueDeathRefusal.outcomeDescription>
```

2024-04-27 11:41 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <NeurosisPulse.label>pulso de neurose</NeurosisPulse.label>
```suggestion
  <NeurosisPulse.label>pulso neurótico</NeurosisPulse.label>
```

2024-04-27 12:13 UTC, Froxynox commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <Brainwipe.label>limpesa cerebral</Brainwipe.label>
ixi, vou ver com os outro então. Se eles preferirem esse termo ai, ai eu troco

2024-04-27 12:15 UTC, Froxynox commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <Brainwipe.description>Apaga as memórias da pessoa. Eventos traumaticos serão esquecidos. Prisioneiros irão esquecer de suas submissões, sendo mais fácil de recrutar, mesmo se ele estava inebálavel
´´sua lealmente´´?

2024-04-27 18:47 UTC, IssMoW requested changes
Sempre que desejar use aplicativos de tradução, apesar de tornar a leitura robótica lhe renderá ótimas idéias. (Claro que você não irá apenas dar ctr c/ crt v) O intuito é garimpar idéias :D

Caso não compreenda o significado do que foi escrito há uma probabilidade de estar fora de contexto.

Se não concordar com alguma das alterações não hesite em falar.

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonAnimals.label>desenhar animais</SummonAnimals.label>
```suggestion
  <SummonAnimals.label>atrair animais</SummonAnimals.label>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonAnimals.description>Cria um pulso psíquico que irá desenhar um distante rebanho de animais da área local. Você consegue caçar ou fazer o que bem entender. Se não feito corretamente, isso pod
```suggestion
  <SummonAnimals.description>Cria um pulso psíquico que irá atrair um rebanho de animais da área local. Você poderá caça-los ou fazer o que bem entender. No entanto se não feito corretamente, poderá atrair caçadores de humanos infectados por scaria. </SummonAnimals.description>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonAnimals.outcomeDescription>Com a atual qualidade do ritual, existe a chance de {0} que os animais cheguem como caçadores de humanos.</SummonAnimals.outcomeDescription>
```suggestion
  <SummonAnimals.outcomeDescription>Com a atual qualidade ritual, a chance de que cheguem animais caçadores de humanos é de {0} </SummonAnimals.outcomeDescription>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeasts.label>desenhar besta carnal</SummonFleshbeasts.label>
```suggestion
  <SummonFleshbeasts.label>atrair besta carnal</SummonFleshbeasts.label>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeasts.description>Cria um pulso psíquico que irá desenhar bestas carnais cavando para a superfície e emergir perto dos seus inimigos. Eles irão atacar qualquer um que encontrarem, incl
```suggestion
  <SummonFleshbeasts.description>Cria um pulso psíquico que irá atrair bestas carnais que estão abaixo da superfície, elas emergirão perto dos seus inimigos. Atacando qualquer um que encontrarem, incluindo seus inimigos e aliados. Bestas carnais podem ser capturadas e estudadas, ou podem ser esquaterjadas pela carne retorcida.</SummonFleshbeasts.description>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeasts.letterAIArrivedText>Eles pretendem usar ritual psíquico para invocar bestas carnais horríveis para atacar você.</SummonFleshbeasts.letterAIArrivedText>
```suggestion
  <SummonFleshbeasts.letterAIArrivedText>Eles pretendem usar um ritual psíquico para invocar horríveis bestas carnais para lhe atacar.</SummonFleshbeasts.letterAIArrivedText>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeasts.letterAICompleteText>Bestas carnais estão rasgando o caminho para fora do chão. Prepare-se para os ataques deles!</SummonFleshbeasts.letterAICompleteText>
```suggestion
  <SummonFleshbeasts.letterAICompleteText>Bestas carnais estão rasgando seu caminho para fora do chão. Prepare-se para os ataques!</SummonFleshbeasts.letterAICompleteText>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeasts.outcomeDescription>Cria um pulso psíquico que irá desenhar uma horda de bestas carnais.</SummonFleshbeasts.outcomeDescription>
```suggestion
  <SummonFleshbeasts.outcomeDescription>Crie um pulso psíquico que atrairá uma horda de bestas carnais.</SummonFleshbeasts.outcomeDescription>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeastsPlayer.label>desenhar besta carnal</SummonFleshbeastsPlayer.label>
```suggestion
  <SummonFleshbeastsPlayer.label>atrair besta carnal</SummonFleshbeastsPlayer.label>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeastsPlayer.description>Cria um pulso psíquico que irá desenhar bestas carnais cavando para a superfície e emergir perto dos seus inimigos. Eles irão atacar qualquer um que encontrarem
```suggestion
  <SummonFleshbeastsPlayer.description>Cria um pulso psíquico que irá atrair bestas carnais que estão abaixo da superfície, elas emergirão perto dos seus inimigos. Atacando qualquer um que encontrarem, incluindo seus inimigos e aliados. Bestas carnais podem ser capturadas e estudadas, ou podem ser esquaterjadas pela carne retorcida.
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonFleshbeastsPlayer.outcomeDescription>Uma melhor qualidade do ritual irá atrair mais bestas carnais.</SummonFleshbeastsPlayer.outcomeDescription>
```suggestion
  <SummonFleshbeastsPlayer.outcomeDescription>Uma alta qualidade ritual atrairá mais bestas carnais.</SummonFleshbeastsPlayer.outcomeDescription>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonPitGate.label>provocação do portal do abismo</SummonPitGate.label>
```suggestion
  <SummonPitGate.label>provocando o portal do abismo</SummonPitGate.label>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonPitGate.description>Use um pulso psíquico para provocar bestas carnais debaixo da terra para abrir uma massiva abertura do portal do abismo no chão em algum lugar da área local. O enorme bur
```suggestion
  <SummonPitGate.description>Use um pulso psíquico para provocar bestas carnais abaixo da superfície afim de abrir uma massiva passagem em algum lugar da área local. O enorme abismo irá levar a uma caverna infestada por bestas carnais, a qual poderá ser explorada por recursos.</SummonPitGate.description>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonPitGate.outcomeDescription>Uma melhor qualidade do ritual ira atrair mais bestas carnais. A besta carnal pode ser capturada e estudada, ou esquaterjada para carne torcida.</SummonPitGate.out
```suggestion
  <SummonPitGate.outcomeDescription>Uma alta qualidade ritual atrairá mais bestas carnais. Elas podem ser capturadas e estudadas, ou esquartejadas pela carne retorcida.</SummonPitGate.outcomeDescription>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonShamblers.label>desenhar trôpego</SummonShamblers.label>
```suggestion
  <SummonShamblers.label>atrair trôpegos</SummonShamblers.label>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonShamblers.description>Cria um pulso psíqico que irá desenhar uma horda de cadáveres animados em direção a sua área local. enquanto eles atacam qualquer humano que vejam, eles não irão atacar
```suggestion
  <SummonShamblers.description>Cria um pulso psíqico que atrairá uma horda de cadáveres reanimados em direção a sua área. Atacando qualquer humano que vejam, eles não irão atacar sua colônia diretamente. Você pode captura-los para estudos.</SummonShamblers.description>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <SummonShamblers.outcomeDescription>Quanto mais alto a qualidade do ritual, mais trôpegos irão ser invocados.</SummonShamblers.outcomeDescription>
```suggestion
  <SummonShamblers.outcomeDescription>Quanto maior a qualidade ritual, mais trôpegos serão invocados.</SummonShamblers.outcomeDescription>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <VoidProvocation.description>Comungar psíquicamente com o vazio, atraindo uma entidade que pode ser capturada e estudada. Existe uma chance que o invocador irá cair em uma coma por muitos dias.</Vo
```suggestion
  <VoidProvocation.description>Comungar psíquicamente com o vazio, atraindo uma entidade que poderá ser capturada e estudada. Existe uma chance do invocador cair em coma por várias horas.</VoidProvocation.description>
```

2024-04-27 18:47 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <VoidProvocation.outcomeDescription>Com a atual qualidade, existe a chance de {0} do invocador será recebido com um choque sombrio psíquico.</VoidProvocation.outcomeDescription>
```suggestion
  <VoidProvocation.outcomeDescription>Com a qualidade atual, há {0} chance de o invocador receber um choque psíquico sombrio.</VoidProvocation.outcomeDescription>
```

2024-04-28 10:59 UTC, IssMoW commented on Anomaly/DefInjected/PsychicRitualDef/PsychicRituals.xml
> +  <PleasurePulse.label>pulso de prazer</PleasurePulse.label>
```suggestion
  <PleasurePulse.label>pulso extasiante</PleasurePulse.label>
```

2025-03-16 21:08 UTC, LoboMetalurgico commented
Stale

2025-03-16 21:08 UTC, closed without merging