Feat/anomaly
Ludeon/RimWorld-PortugueseBrazilian pull request #312
Opened 2024-07-01 15:46 UTC by lenhare

### **📝 Alterações Propostas:**
Update AnomalyPlaytests.xml and Menus_Main.xml

### **📜 Requisitos:**

 - [X] Você testou as traduções antes de publicar o pull request?
 - [X] Você verificou se outro pull request tem a mesma proposta que o seu?
 - [X] Você verificou se sua fork e sua branch estão atualizadas?
 - [ ] Você já faz parte da equipe de tradução?

2024-07-01 15:51 UTC, lenhare commented
O teste:
![image](https://github.com/Ludeon/RimWorld-PortugueseBrazilian/assets/17187267/85e73ea5-127b-4ffd-8093-da40d2cd015f)

2024-07-02 14:20 UTC, LoboMetalurgico requested changes
Olá, obrigado pelo seu Pull Request.

Antes de podermos revisar a tradução em si, precisamos que verifique alguns detalhes importantes.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +﻿<?xml version="1.0" encoding="utf-8"?>
```suggestion
﻿<?xml version="1.0" encoding="UTF-8"?>
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <DifficultyAnomalySection>Anomalia</DifficultyAnomalySection>
```suggestion
  <!-- EN: Anomaly -->
  <DifficultyAnomalySection>Anomalia</DifficultyAnomalySection>
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <DifficultyAnomalySection>Anomalia</DifficultyAnomalySection>
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreats_Label>Ameaças de Anomalia</Difficulty_AnomalyThreats_Label>
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreats_Info>Ajuste a porcentagem de ameaças principais que estarão relacionadas à Anomalia.</Difficulty_AnomalyThreats_Info>
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreatsInactive_Label>Ameaças de Anomalia (inativas)</Difficulty_AnomalyThreatsInactive_Label>
```suggestion
  <!-- EN: Anomaly threats (inactive) -->
  <Difficulty_AnomalyThreatsInactive_Label>Ameaças de Anomalia (inativas)</Difficulty_AnomalyThreatsInactive_Label>
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreatsInactive_Label>Ameaças de Anomalia (inativas)</Difficulty_AnomalyThreatsInactive_Label>
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreatsInactive_Info>Ajuste a porcentagem de ameaças principais que estarão relacionadas à Anomalia quando o monólito não estiver ativo. Apenas certos incidentes menores de Anoma
```suggestion
  <!-- EN: Adjust the percentage of major threats that will be Anomaly-related when the monolith is not active. Only certain minor Anomaly incidents can occur when the monolith is inactive. -->
  <Difficulty_AnomalyThreatsInactive_Info>Ajuste a porcentagem de ameaças principais que estarão relacionadas à Anomalia quando o monólito não estiver ativo. Apenas certos incidentes menores de Anomalia podem ocorrer quando o monólito está inativo.</Difficulty_AnomalyThreatsInactive_Info>
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreatsInactive_Info>Ajuste a porcentagem de ameaças principais que estarão relacionadas à Anomalia quando o monólito não estiver ativo. Apenas certos incidentes menores de Anoma
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreatsActive_Label>Ameaças de Anomalia (ativas)</Difficulty_AnomalyThreatsActive_Label>
```suggestion
  <!-- EN: Anomaly threats (active) -->
  <Difficulty_AnomalyThreatsActive_Label>Ameaças de Anomalia (ativas)</Difficulty_AnomalyThreatsActive_Label>
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreatsActive_Label>Ameaças de Anomalia (ativas)</Difficulty_AnomalyThreatsActive_Label>
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_AnomalyThreatsActive_Info>Ajuste a porcentagem de ameaças principais que estarão relacionadas à Anomalia quando o monólito estiver ativo. Com as configurações atuais:\n  - {0} das ameaç
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_ChildShamblersAllowed_Label>Abominações infantis</Difficulty_ChildShamblersAllowed_Label>
```suggestion
  <!-- EN: Child shamblers -->
  <Difficulty_ChildShamblersAllowed_Label>Abominações infantis</Difficulty_ChildShamblersAllowed_Label>
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_ChildShamblersAllowed_Label>Abominações infantis</Difficulty_ChildShamblersAllowed_Label>
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_ChildShamblersAllowed_Info>Abominações infantis reanimadas às vezes aparecerão.</Difficulty_ChildShamblersAllowed_Info>
```suggestion
  <!-- EN: Reanimated child shamblers will sometimes appear. -->
  <Difficulty_ChildShamblersAllowed_Info>Abominações infantis reanimadas às vezes aparecerão.</Difficulty_ChildShamblersAllowed_Info>
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_ChildShamblersAllowed_Info>Abominações infantis reanimadas às vezes aparecerão.</Difficulty_ChildShamblersAllowed_Info>
Nunca apague um texto base.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_StudyEfficiency_Info>Adicione um multiplicador à quantidade de pesquisa obtida ao estudar entidades sobrenaturais.</Difficulty_StudyEfficiency_Info>
```suggestion
```

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <Difficulty_StudyEfficiency_Info>Adicione um multiplicador à quantidade de pesquisa obtida ao estudar entidades sobrenaturais.</Difficulty_StudyEfficiency_Info>
Não adicione textos que não estão no arquivo de tradução do github sem os textos base, pois não tem como verificarmos.

Se o arquivo estiver desatualizado, notifique via Discord/Issue e será atualizado o quanto antes.

2024-07-02 14:20 UTC, LoboMetalurgico commented on Anomaly/Keyed/Menus_Main.xml
> +  <SetToStandardPlaystyle>Definir para estilo de jogo padrão</SetToStandardPlaystyle>
```suggestion
```

2025-03-15 18:47 UTC, LoboMetalurgico commented
Stale

2025-03-15 18:47 UTC, closed without merging